# Generated by Django 5.0.1 on 2026-07-29 11:43

import apps.insta_reports.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("integrations", "0046_igaccountconnection_biography_and_more"),
        ("workspace", "0002_workspace_plan_workspace_workspaces_plan_c35e25_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IGVideoFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "external_account_id",
                    models.CharField(max_length=255, verbose_name="IG 계정 ID"),
                ),
                ("shortcode", models.CharField(max_length=64, verbose_name="게시물 shortcode")),
                (
                    "schema_version",
                    models.PositiveSmallIntegerField(verbose_name="피처 스키마 버전"),
                ),
                ("features_json", models.JSONField(verbose_name="추출 피처")),
                ("model_name", models.CharField(blank=True, default="", max_length=100)),
                ("tokens_in", models.PositiveIntegerField(default=0)),
                ("tokens_out", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "영상 피처 캐시",
                "verbose_name_plural": "영상 피처 캐시 목록",
                "db_table": "insta_report_video_feature",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstagramReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "ig_username",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="IG username"
                    ),
                ),
                (
                    "ig_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="IG 표시명"
                    ),
                ),
                (
                    "followers_snapshot",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="팔로워 수"),
                ),
                (
                    "media_count_snapshot",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="게시물 수"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "대기"),
                            ("running", "진행 중"),
                            ("succeeded", "완료"),
                            ("failed", "실패"),
                            ("cancelled", "취소"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("queued", "대기 중"),
                            ("collecting", "게시물 모으는 중"),
                            ("metrics", "숫자 계산 중"),
                            ("preparing", "영상 내려받는 중"),
                            ("extracting", "영상 분석 중"),
                            ("comments", "댓글 분석 중"),
                            ("synthesizing", "인사이트 쓰는 중"),
                            ("verifying", "검수하는 중"),
                            ("rendering", "리포트 만드는 중"),
                            ("exporting", "PDF 만드는 중"),
                            ("done", "완료"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="진행 단계",
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0, verbose_name="진행률(%)")),
                (
                    "message",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="진행 메시지"
                    ),
                ),
                (
                    "stage_started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="현재 단계 시작"),
                ),
                (
                    "stage_expected_seconds",
                    models.PositiveIntegerField(default=0, verbose_name="현재 단계 예상 소요(초)"),
                ),
                ("metrics_json", models.JSONField(blank=True, null=True, verbose_name="지표(S2)")),
                (
                    "aggregates_json",
                    models.JSONField(blank=True, null=True, verbose_name="집계(S5)"),
                ),
                (
                    "slots_json",
                    models.JSONField(blank=True, null=True, verbose_name="서술 슬롯(S6·S7)"),
                ),
                (
                    "gate_meta",
                    models.JSONField(blank=True, default=dict, verbose_name="검증 게이트 로그"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=apps.insta_reports.models.report_pdf_path,
                        verbose_name="PDF",
                    ),
                ),
                (
                    "pdf_bytes",
                    models.PositiveIntegerField(default=0, verbose_name="PDF 크기(byte)"),
                ),
                (
                    "posts_analyzed",
                    models.PositiveIntegerField(default=0, verbose_name="분석 게시물 수"),
                ),
                (
                    "reels_with_views",
                    models.PositiveIntegerField(default=0, verbose_name="조회수 있는 릴스 수"),
                ),
                (
                    "videos_analyzed",
                    models.PositiveIntegerField(default=0, verbose_name="AI 영상 분석 수"),
                ),
                (
                    "comments_analyzed",
                    models.PositiveIntegerField(default=0, verbose_name="분석 댓글 수"),
                ),
                (
                    "period_from",
                    models.DateField(blank=True, null=True, verbose_name="분석 기간 시작"),
                ),
                (
                    "period_to",
                    models.DateField(blank=True, null=True, verbose_name="분석 기간 종료"),
                ),
                (
                    "cost_usd",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=8, verbose_name="원가(USD)"
                    ),
                ),
                (
                    "tokens_json",
                    models.JSONField(blank=True, default=dict, verbose_name="토큰 원장"),
                ),
                (
                    "elapsed_seconds",
                    models.PositiveIntegerField(default=0, verbose_name="소요(초)"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VIEWS_UNAVAILABLE", "조회수 수집 실패"),
                            ("NO_POSTS", "게시물 없음"),
                            ("NOT_ENOUGH_REELS", "분석 가능한 릴스 부족"),
                            ("TOKEN_INVALID", "인스타 연결 만료"),
                            ("EXTRACT_FAILED", "영상 분석 실패"),
                            ("SYNTH_FAILED", "인사이트 작성 실패"),
                            ("RENDER_FAILED", "리포트 생성 실패"),
                            ("PDF_FAILED", "PDF 변환 실패"),
                            ("TIMEOUT", "시간 초과"),
                            ("INTERNAL", "내부 오류"),
                        ],
                        default="",
                        max_length=32,
                        verbose_name="실패 코드",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="실패 상세(내부)"),
                ),
                ("celery_task_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "quota_consumed",
                    models.BooleanField(db_index=True, default=True, verbose_name="이용 횟수 차감"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "인스타 성장 리포트",
                "verbose_name_plural": "인스타 성장 리포트 목록",
                "db_table": "insta_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportAiCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(max_length=128, unique=True, verbose_name="캐시 키(sha256)"),
                ),
                ("kind", models.CharField(db_index=True, max_length=40, verbose_name="종류")),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("payload_json", models.JSONField(verbose_name="캐시 값")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "리포트 AI 캐시",
                "verbose_name_plural": "리포트 AI 캐시 목록",
                "db_table": "insta_report_ai_cache",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="igvideofeature",
            constraint=models.UniqueConstraint(
                fields=("external_account_id", "shortcode", "schema_version"),
                name="uq_igfeature_acct_sc_ver",
            ),
        ),
        migrations.AddField(
            model_name="instagramreport",
            name="ig_connection",
            field=models.ForeignKey(
                blank=True,
                help_text="연동이 해제돼도 리포트는 남는다(아래 스냅샷 필드로 표시).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="insta_reports",
                to="integrations.igaccountconnection",
                verbose_name="대상 IG 연동",
            ),
        ),
        migrations.AddField(
            model_name="instagramreport",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="insta_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="요청자",
            ),
        ),
        migrations.AddField(
            model_name="instagramreport",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insta_reports",
                to="workspace.workspace",
                verbose_name="워크스페이스",
            ),
        ),
        migrations.AddIndex(
            model_name="instagramreport",
            index=models.Index(
                fields=["workspace", "-created_at"], name="insta_repor_workspa_6314b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instagramreport",
            index=models.Index(
                fields=["ig_connection", "-created_at"], name="insta_repor_ig_conn_51c1ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instagramreport",
            index=models.Index(
                fields=["status", "created_at"], name="insta_repor_status_2b216c_idx"
            ),
        ),
    ]
