# Generated by Django 5.0.1 on 2026-08-03 12:53

import apps.insta_reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insta_reports", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instagramreport",
            name="pdf_bytes",
        ),
        migrations.RemoveField(
            model_name="instagramreport",
            name="pdf_file",
        ),
        migrations.AddField(
            model_name="instagramreport",
            name="html_bytes",
            field=models.PositiveIntegerField(default=0, verbose_name="HTML 크기(byte)"),
        ),
        migrations.AddField(
            model_name="instagramreport",
            name="html_file",
            field=models.FileField(
                blank=True,
                help_text="자기완결 HTML(썸네일 data-URI + Chart.js 인라인) — 인증 다운로드로만 제공",
                max_length=500,
                null=True,
                upload_to=apps.insta_reports.models.report_html_path,
                verbose_name="리포트 HTML",
            ),
        ),
        migrations.AlterField(
            model_name="instagramreport",
            name="error_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VIEWS_UNAVAILABLE", "조회수 수집 실패"),
                    ("NO_POSTS", "게시물 없음"),
                    ("NOT_ENOUGH_REELS", "분석 가능한 릴스 부족"),
                    ("TOKEN_INVALID", "인스타 연결 만료"),
                    ("EXTRACT_FAILED", "영상 분석 실패"),
                    ("SYNTH_FAILED", "인사이트 작성 실패"),
                    ("RENDER_FAILED", "리포트 생성 실패"),
                    ("TIMEOUT", "시간 초과"),
                    ("INTERNAL", "내부 오류"),
                ],
                default="",
                max_length=32,
                verbose_name="실패 코드",
            ),
        ),
        migrations.AlterField(
            model_name="instagramreport",
            name="stage",
            field=models.CharField(
                choices=[
                    ("queued", "대기 중"),
                    ("collecting", "게시물 모으는 중"),
                    ("metrics", "숫자 계산 중"),
                    ("preparing", "영상 내려받는 중"),
                    ("extracting", "영상 분석 중"),
                    ("comments", "댓글 분석 중"),
                    ("synthesizing", "인사이트 쓰는 중"),
                    ("verifying", "검수하는 중"),
                    ("rendering", "리포트 만드는 중"),
                    ("exporting", "파일로 저장하는 중"),
                    ("done", "완료"),
                ],
                default="queued",
                max_length=20,
                verbose_name="진행 단계",
            ),
        ),
    ]
