# Generated by Django 5.0.1 on 2026-04-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_jobs", "0004_aijob_llm_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aijob",
            name="llm_model",
            field=models.CharField(
                choices=[
                    ("gemma", "Gemma (자체 H100, 기본)"),
                    ("deepseek", "DeepSeek V4-Flash (외부 API, 폴백/오버플로우)"),
                    ("gpt5", "GPT-5.4"),
                ],
                default="gemma",
                max_length=20,
                verbose_name="LLM 모델",
            ),
        ),
    ]
