# Generated by Django 5.0.1 on 2026-06-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_jobs", "0007_aijob_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aijob",
            name="llm_model",
            field=models.CharField(
                choices=[
                    ("gemma", "Gemma (자체 H100, 폴백/오버플로우)"),
                    ("deepseek", "DeepSeek V4-Flash (외부 API, 기본)"),
                    ("gpt5", "GPT-5.4"),
                ],
                default="deepseek",
                max_length=20,
                verbose_name="LLM 모델",
            ),
        ),
    ]
