# Generated by Django 5.0.1 on 2026-06-04 09:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_jobs", "0008_alter_aijob_llm_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="aijob",
            name="stage",
            field=models.CharField(
                choices=[
                    ("queued", "대기"),
                    ("labeling_images", "이미지 분석"),
                    ("preparing_prompt", "프롬프트 준비"),
                    ("calling_model", "모델 호출"),
                    ("parsing_response", "응답 파싱"),
                    ("resolving_images", "이미지 검색"),
                    ("fetching_source", "원본 페이지 다운로드"),
                    ("converting", "블록 변환"),
                    ("reuploading_images", "이미지 재업로드"),
                    ("creating_page", "페이지 생성"),
                    ("completed", "완료"),
                ],
                default="queued",
                max_length=30,
                verbose_name="진행 단계",
            ),
        ),
        migrations.CreateModel(
            name="AiSourceImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="ai_source_images/%Y/%m/", verbose_name="이미지"),
                ),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("size", models.PositiveIntegerField(default=0, verbose_name="크기(byte)")),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("original_name", models.CharField(blank=True, default="", max_length=500)),
                (
                    "content_hash",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("labeled", models.BooleanField(default=False, verbose_name="라벨링 완료")),
                ("usable", models.BooleanField(default=False, verbose_name="페이지 사용 가능")),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[("content", "콘텐츠(페이지 배치)"), ("concept", "컨셉(참고용)")],
                        default="",
                        max_length=20,
                        verbose_name="용도",
                    ),
                ),
                ("summary", models.TextField(blank=True, default="", verbose_name="이미지 요약")),
                ("suggested_use", models.CharField(blank=True, default="", max_length=200)),
                (
                    "quality_flags",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{blurry, low_res, has_text, nsfw}",
                        verbose_name="품질 플래그",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="업로드 시점엔 비어 있고, 생성 작업 생성 시 연결된다.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_images",
                        to="ai_jobs.aijob",
                        verbose_name="연결된 작업",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_source_images",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 소스 이미지",
                "verbose_name_plural": "AI 소스 이미지 목록",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"], name="ai_jobs_ais_user_id_a021a4_idx"
                    )
                ],
            },
        ),
    ]
