# Generated by Django 5.0.1 on 2026-07-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_jobs", "0010_alter_aijob_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aijob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("bio_remake", "바이오 리메이크"),
                    ("theme_generation", "테마 생성"),
                    ("copy_generation", "카피 생성"),
                    ("external_import", "외부 페이지 가져오기"),
                    ("dm_campaign_assist", "DM 캠페인 폼 자동완성"),
                    ("dm_opening_diversify", "오프닝 DM 다양화"),
                ],
                default="bio_remake",
                max_length=30,
                verbose_name="작업 유형",
            ),
        ),
    ]
