# Generated by Django 5.0.1 on 2026-02-04 14:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspace", "0002_workspace_plan_workspace_workspaces_plan_c35e25_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageCounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("comments_collected", models.IntegerField(default=0)),
                ("dm_sent", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_counters",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "usage_counters",
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "year", "month"], name="usage_count_workspa_ee3d90_idx"
                    ),
                    models.Index(fields=["year", "month"], name="usage_count_year_cc2dc4_idx"),
                ],
                "unique_together": {("workspace", "year", "month")},
            },
        ),
    ]
