# Generated by Django 5.0.1 on 2026-05-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagecounter",
            name="comments_moderated",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usagecounter",
            name="videos_published",
            field=models.IntegerField(default=0),
        ),
    ]
