# Generated by Django 5.0.1 on 2026-07-02 03:50
"""
PayApp → 토스페이먼츠 빌링 전환 (파괴적 — 결제 고객 0명 확인 후 진행).

- payapp 필드 제거, 토스 빌링키/스냅샷/dunning/트라이얼 필드 추가
- PayAppWebhookLog → TossWebhookLog 교체
- 기존 구독 행 전체에 toss_customer_key 백필 (유저당 고정 랜덤 키)

⚠️ 운영 배포 전 1회: `python manage.py cancel_rebills --execute`로
   PayApp 측 잔존 정기결제를 먼저 해지할 것 (커맨드는 이후 커밋에서 삭제됨).
"""

import uuid

import django.db.models.deletion
from django.db import migrations, models


def backfill_customer_keys(apps, schema_editor):
    UserSubscription = apps.get_model("billing", "UserSubscription")
    to_update = []
    for sub in UserSubscription.objects.filter(toss_customer_key__isnull=True).only("id"):
        sub.toss_customer_key = f"tf_{uuid.uuid4().hex}"
        to_update.append(sub)
    if to_update:
        UserSubscription.objects.bulk_update(to_update, ["toss_customer_key"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_plan_restructure"),
    ]

    operations = [
        migrations.CreateModel(
            name="TossWebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="PAYMENT_STATUS_CHANGED / CANCEL_STATUS_CHANGED / BILLING_DELETED 등",
                        max_length=50,
                        verbose_name="이벤트 타입",
                    ),
                ),
                (
                    "dedup_key",
                    models.CharField(
                        help_text="본문 구조 기반 중복 방지 키", max_length=255, unique=True
                    ),
                ),
                (
                    "payment_key",
                    models.CharField(blank=True, db_index=True, default="", max_length=200),
                ),
                ("order_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "raw_data",
                    models.JSONField(default=dict, verbose_name="수신 데이터 (빌링키는 해시 치환)"),
                ),
                ("processed", models.BooleanField(default=False)),
                ("process_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "토스 웹훅 로그",
                "verbose_name_plural": "토스 웹훅 로그 목록",
                "db_table": "toss_webhook_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="PayAppWebhookLog",
        ),
        migrations.RemoveField(
            model_name="paymenthistory",
            name="pay_type_display",
        ),
        migrations.RemoveField(
            model_name="paymenthistory",
            name="payapp_mul_no",
        ),
        migrations.RemoveField(
            model_name="paymenthistory",
            name="payapp_rebill_no",
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="payapp_pay_url",
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="payapp_rebill_expire",
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="payapp_rebill_no",
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="card_company",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="card_number_masked",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="failure_code",
            field=models.CharField(
                blank=True, default="", help_text="토스 승인 거절 코드", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="failure_message",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="toss_idempotency_key",
            field=models.CharField(
                blank=True,
                help_text="승인 API Idempotency-Key (UUID4) — 모호 실패 재시도 시 재사용",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="toss_order_id",
            field=models.CharField(
                blank=True,
                help_text="우리가 생성하는 주문 ID — 과금 시도 멱등/소유권 키",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="토스 orderId",
            ),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="toss_payment_key",
            field=models.CharField(
                blank=True,
                help_text="승인 응답의 paymentKey — 취소/조회에 사용",
                max_length=200,
                null=True,
                unique=True,
                verbose_name="토스 paymentKey",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="_encrypted_toss_billing_key",
            field=models.TextField(blank=True, default="", verbose_name="토스 빌링키 (암호문)"),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="billing_key_issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="card_company",
            field=models.CharField(
                blank=True,
                default="",
                help_text="빌링키 발급 응답의 cardCompany (표시용)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="card_number_masked",
            field=models.CharField(
                blank=True,
                default="",
                help_text="마스킹된 카드번호 (표시용, 예: 433012******123*)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="extra_ig_accounts",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="프로 전용 — 계정당 +9,900원/월 갱신 합산",
                verbose_name="추가 IG 계정 수",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="last_billing_error",
            field=models.CharField(
                blank=True,
                default="",
                help_text="마지막 과금 실패 사유 (토스 code: message)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="monthly_amount_snapshot",
            field=models.IntegerField(
                blank=True,
                help_text="구독 시작 시점 판매가 고정 (프로모 그랜드파더링). 갱신 청구 기본액",
                null=True,
                verbose_name="월 청구액 스냅샷",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="next_billing_retry_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="past_due 재시도 예정 시각 (D+1/D+3/D+5)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="pending_amount_snapshot",
            field=models.IntegerField(
                blank=True, help_text="예약 플랜의 예약 시점 판매가", null=True
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="pending_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="다운그레이드 예약 — 다음 갱신 시점에 적용",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_subscriptions",
                to="billing.subscriptionplan",
                verbose_name="예약된 플랜 변경",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="renewal_attempts",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="현재 주기 갱신 과금 시도 횟수 (성공 시 0으로 리셋)"
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="toss_billing_key_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="BILLING_DELETED 웹훅(빌링키만 옴) 역조회용 — Fernet 암호문은 비결정적",
                max_length=64,
                null=True,
                verbose_name="빌링키 SHA-256",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="toss_customer_key",
            field=models.CharField(
                blank=True,
                help_text="유저당 고정 랜덤 키 (tf_{uuid4.hex}). 유추 불가해야 함 — 외부 노출 금지",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="토스 customerKey",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="trial_used_at",
            field=models.DateTimeField(
                blank=True,
                help_text="카드등록 무료 1개월은 1인 1회 — 다운그레이드돼도 지우지 않음(어뷰징 방어)",
                null=True,
                verbose_name="프로 트라이얼 사용 시각",
            ),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="receipt_url",
            field=models.URLField(
                blank=True,
                help_text="토스 receipt.url — 영수증 URL",
                max_length=500,
                null=True,
                verbose_name="매출전표 URL",
            ),
        ),
        migrations.RunPython(backfill_customer_keys, migrations.RunPython.noop),
    ]
