# Generated by Django 5.0.1 on 2026-07-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0015_toss_billing"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="ig_account_activation_changed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="하루 1회 제한용 — 마지막으로 IG 계정 활성화 조정한 시각",
                null=True,
                verbose_name="IG 계정 활성화 변경 일시",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="ig_activation_review_needed",
            field=models.BooleanField(
                default=False,
                help_text="갱신 시 허용량 초과로 자동 비활성이 발생 → 사용자가 활성 계정을 다시 고르도록 유도. POST 시 해제",
                verbose_name="IG 활성 계정 재선택 필요",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="pending_extra_ig_accounts",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="추가 계정 '축소' 예약 — 다음 갱신 시점에 extra_ig_accounts 로 확정. null=예약 없음",
                null=True,
                verbose_name="예약된 추가 IG 계정 수",
            ),
        ),
    ]
