# Generated by Django 5.0.1 on 2026-07-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0018_retire_pro_plus_to_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="last_pause_at",
            field=models.DateTimeField(
                blank=True,
                help_text="연 1회 제한(can_pause) 판정용 — 재개해도 지우지 않음",
                null=True,
                verbose_name="마지막 정지 요청 시각",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="pause_ends_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="paused 구독의 자동 유료 재개(+과금) 시각. = 잔여 유료기간 종료일 + paused_months",
                null=True,
                verbose_name="정지 자동 재개 예정일",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="pause_resume_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="자동 결제 재개 사전 고지 중복 방지",
                null=True,
                verbose_name="재개 3일 전 고지 발송 시각",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="paused_months",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="1/2/3. paused 상태에서만 유효",
                null=True,
                verbose_name="정지 개월 수",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="retention_discount_pending",
            field=models.BooleanField(
                default=False,
                help_text="True면 다음 1회 갱신에 RETENTION_DISCOUNT_PERCENT 적용 후 자동 소멸",
                verbose_name="다음 갱신 할인 대기",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="retention_discount_used_at",
            field=models.DateTimeField(
                blank=True,
                help_text="1인 1회 — 부여되면 기록, 재부여 차단(어뷰징 방어)",
                null=True,
                verbose_name="리텐션 할인 사용 시각",
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("past_due", "Past Due"),
                    ("trialing", "Trialing"),
                    ("paused", "Paused"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
