# Generated by Django 5.0.1 on 2026-07-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0019_usersubscription_last_pause_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPaidCohortSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("snapshot_date", models.DateField(db_index=True, verbose_name="스냅샷 날짜(KST)")),
                (
                    "cohort_month",
                    models.DateField(
                        help_text="해당 회원의 첫 PAID paid_at 의 KST 월초일 (예: 2026-05-01)",
                        verbose_name="코호트 월",
                    ),
                ),
                (
                    "paying_users",
                    models.PositiveIntegerField(default=0, verbose_name="유료 유지 인원"),
                ),
                ("mrr", models.BigIntegerField(default=0, verbose_name="코호트 MRR (원)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "일별 결제 코호트 스냅샷",
                "verbose_name_plural": "일별 결제 코호트 스냅샷 목록",
                "db_table": "daily_paid_cohort_snapshots",
                "ordering": ["-snapshot_date", "cohort_month"],
            },
        ),
        migrations.CreateModel(
            name="DailySubscriptionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("snapshot_date", models.DateField(unique=True, verbose_name="스냅샷 날짜(KST)")),
                (
                    "plan_status_counts",
                    models.JSONField(
                        default=dict,
                        help_text='{"pro": {"active": 120, "trialing": 14, ...}, ...} — 전 플랜(free 포함)',
                        verbose_name="플랜×상태 인원",
                    ),
                ),
                (
                    "paying_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="free/admin 제외 ACTIVE 구독 수",
                        verbose_name="유료 ACTIVE 수",
                    ),
                ),
                (
                    "trialing_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="free/admin 제외 TRIALING 구독 수",
                        verbose_name="체험 중 수",
                    ),
                ),
                (
                    "cancel_scheduled_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="CANCELLED + 주기 남음 (free/admin 제외)",
                        verbose_name="취소 예약 수",
                    ),
                ),
                ("past_due_count", models.PositiveIntegerField(default=0, verbose_name="미납 수")),
                (
                    "mrr_total",
                    models.BigIntegerField(
                        default=0,
                        help_text="유료 ACTIVE 의 Coalesce(snapshot, 판매가) 합 + 추가 IG 계정 매출",
                        verbose_name="MRR (원)",
                    ),
                ),
                (
                    "extra_ig_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="ACTIVE pro 의 extra_ig_accounts 합",
                        verbose_name="추가 IG 계정 합",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "일별 구독 스냅샷",
                "verbose_name_plural": "일별 구독 스냅샷 목록",
                "db_table": "daily_subscription_snapshots",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="dailypaidcohortsnapshot",
            constraint=models.UniqueConstraint(
                fields=("snapshot_date", "cohort_month"), name="uniq_snapshot_cohort"
            ),
        ),
    ]
