# Generated by Django 5.0.1 on 2026-07-28 09:42

from django.db import migrations, models
from django.db.models import F


def backfill_refunded_at(apps, schema_editor):
    """기존 REFUNDED 행의 환불 시각을 paid_at(없으면 created_at)으로 백필.

    전액 환불은 원 행의 status 만 뒤집던 구조라 실제 환불 시각이 어디에도 없다 —
    결제 시점으로 근사한다. 그 결과 **과거 환불은 결제가 일어난 기간에 잡힌다**
    (미래 환불부터 정확한 환불 시점 귀속). 배포 시점 prod 대상 13행.
    """
    PaymentHistory = apps.get_model("billing", "PaymentHistory")
    qs = PaymentHistory.objects.filter(status="refunded", refunded_at__isnull=True)
    qs.filter(paid_at__isnull=False).update(refunded_at=F("paid_at"))
    qs.filter(paid_at__isnull=True).update(refunded_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0020_dailypaidcohortsnapshot_dailysubscriptionsnapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="refunded_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="status=refunded 로 전환된 시각. 과거 데이터는 paid_at 으로 백필됨(근사).",
                null=True,
                verbose_name="환불 시각",
            ),
        ),
        migrations.RunPython(backfill_refunded_at, migrations.RunPython.noop),
    ]
