# Generated by Django 5.0.1 on 2026-07-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0021_payment_refunded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralcode",
            name="excluded_from_stats",
            field=models.BooleanField(
                default=False,
                help_text="어드민 마케팅 대시보드 집계에서만 제외한다(MKT-14). ⚠️ **고객 동작에는 영향이 없다** — is_redeemable() 이 이 값을 보지 않으므로 제외된 코드도 평소처럼 입력·트라이얼 시작이 된다. 통계 전용 플래그다.",
                verbose_name="집계 제외",
            ),
        ),
    ]
