# Generated by Django 5.0.1 on 2026-08-03 10:08

import django.db.models.deletion
from django.db import migrations, models

# 카드등록 체험은 프로 오퍼다("프로는 카드 등록 시 1개월 무료 체험") — 다운그레이드로
# 현재 플랜이 free 가 된 레거시 행의 체험 플랜 추정 기본값.
_CARD_TRIAL_DEFAULT_PLAN = "pro"


def backfill_trial_history(apps, schema_editor):
    """레거시 행에 trial_plan / cancelled_during_trial_at 을 **best-effort** 복원 (T-1).

    앞으로는 취소·체험 시작 시점에 정확히 기록되지만, 이미 지나간 체험은 흔적이
    일부만 남아 있다. 복원 가능한 만큼만 채운다:

    - trial_plan
      · 쿠폰 체험 → ReferralRedemption.referral_code.target_plan (**정확**, 내구 기록)
      · 카드 체험(trial_used_at 보유) → 현재 유료 플랜이면 그 플랜, free 로 내려갔으면 pro 추정
    - cancelled_during_trial_at
      · 지금도 CANCELLED 이고, **현재 기간이 체험 창**이며 cancelled_at 이 그 안인 행.
        체험 창 판정은 두 종류를 모두 본다:
          카드 체험 → trial_used_at == current_period_start
          쿠폰 체험 → ReferralRedemption.trial_started_at == current_period_start
        (trial_used_at 만 보면 **쿠폰 체험 취소가 전부 누락된다** — prod 3건 중 2건이
         쿠폰이었다. 반대로 창 판정 없이 기간 포함만 보면 '유료 구독 중도 해지'를
         체험 취소로 오인한다.)
      · **이미 만료 다운그레이드된 과거 취소는 복원할 수 없다** — cancelled_at 이 덮이고
        current_period_end 가 지워졌기 때문(그래서 이 필드를 만들었다).
    """
    UserSubscription = apps.get_model("billing", "UserSubscription")
    SubscriptionPlan = apps.get_model("billing", "SubscriptionPlan")
    ReferralRedemption = apps.get_model("billing", "ReferralRedemption")

    default_plan = SubscriptionPlan.objects.filter(name=_CARD_TRIAL_DEFAULT_PLAN).first()
    coupon_plan_by_user = {}
    coupon_start_by_user = {}
    for uid, plan_id, started in ReferralRedemption.objects.values_list(
        "user_id", "referral_code__target_plan_id", "trial_started_at"
    ):
        coupon_plan_by_user[uid] = plan_id
        coupon_start_by_user[uid] = started

    updated = []
    for sub in UserSubscription.objects.select_related("plan").all():
        changed = False

        if sub.trial_plan_id is None:
            coupon_plan_id = coupon_plan_by_user.get(sub.user_id)
            if coupon_plan_id:
                sub.trial_plan_id = coupon_plan_id
                changed = True
            elif sub.trial_used_at is not None:
                if sub.plan_id and sub.plan.name not in ("free", "admin"):
                    sub.trial_plan_id = sub.plan_id
                elif default_plan is not None:
                    sub.trial_plan_id = default_plan.id
                changed = sub.trial_plan_id is not None

        # 현재 기간이 체험 창인가 (카드 체험 또는 쿠폰 체험의 시작 시각과 일치)
        period_start = sub.current_period_start
        in_trial_window = period_start is not None and (
            sub.trial_used_at == period_start
            or coupon_start_by_user.get(sub.user_id) == period_start
        )
        if (
            sub.cancelled_during_trial_at is None
            and sub.status == "cancelled"
            and in_trial_window
            and sub.cancelled_at is not None
            and sub.current_period_end is not None
            and period_start <= sub.cancelled_at < sub.current_period_end
        ):
            sub.cancelled_during_trial_at = sub.cancelled_at
            changed = True

        if changed:
            updated.append(sub)

    if updated:
        UserSubscription.objects.bulk_update(
            updated, ["trial_plan", "cancelled_during_trial_at"], batch_size=500
        )


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0023_add_insta_report_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="cancelled_during_trial_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="체험(TRIALING) 상태에서 구독 취소가 일어난 시각 (T-1). ⚠️ cancelled_at 과 다르다 — cancelled_at 은 ①사용자 취소 ②만료 다운그레이드 ③카드 삭제 강제해지가 **모두 덮어쓰는** 필드라 '체험 중 취소'를 사후에 가려낼 수 없다. 이 필드는 취소 시점에 status==TRIALING 이었을 때만 기록된다. 포함 범위: 사용자의 취소 + 카드 삭제로 인한 강제 해지(결과가 같다). 재체험해도 지우지 않는다(지우면 지나간 기간의 집계가 나중에 줄어든다) — 다만 한 행에 1건만 담기므로 두 번 취소하면 최신 것이 앞의 것을 덮는다.",
                null=True,
                verbose_name="체험 중 취소 시각",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="trial_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="체험을 시작한 플랜 (카드등록 체험·쿠폰 체험 공통). plan 은 만료 시 free 로 바뀌므로 '무슨 플랜 체험이었나'의 내구 기록이 따로 필요하다.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="billing.subscriptionplan",
                verbose_name="체험 대상 플랜",
            ),
        ),
        migrations.RunPython(backfill_trial_history, migrations.RunPython.noop),
    ]
