# Generated by Django 5.0.1 on 2026-08-10 10:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0024_subscription_trial_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="conversion_consent_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="30일 초과 체험(쿠폰 연장)의 첫 결제 전 재동의 시각. null 이면 미동의 — 체험 종료 과금이 차단되고 무료로 전환된다(consent.blocks_first_charge). 체험을 새로 시작하면 초기화된다(지난 체험의 동의가 다음 체험을 통과시키면 안 됨).",
                null=True,
                verbose_name="유료전환 2차 동의 시각",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="conversion_consent_notice_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="중복 발송 방지. 체험 재시작 시 초기화",
                null=True,
                verbose_name="2차 동의 요청 메일(D-14) 발송 시각",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="conversion_consent_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="중복 발송 방지. 체험 재시작 시 초기화",
                null=True,
                verbose_name="2차 동의 리마인드 메일(D-3) 발송 시각",
            ),
        ),
        migrations.CreateModel(
            name="PaymentConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("initial", "결제 화면 동의 (카드 등록 직전)"),
                            ("conversion", "유료전환 2차 동의 (첫 결제 전)"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("plan_name", models.CharField(max_length=30, verbose_name="고지한 플랜 코드명")),
                (
                    "disclosed_first_charge_at",
                    models.DateField(
                        blank=True,
                        help_text="화면에 표시한 날짜 그대로 (KST 기준 날짜). 서버 계산값과 다르면 그 자체가 증거",
                        null=True,
                        verbose_name="고지한 첫 결제일",
                    ),
                ),
                (
                    "disclosed_amount",
                    models.IntegerField(verbose_name="고지한 금액(원, 부가세 포함)"),
                ),
                (
                    "disclosed_recurring_cycle",
                    models.CharField(
                        default="monthly", max_length=20, verbose_name="고지한 결제 주기"
                    ),
                ),
                (
                    "payment_method_type",
                    models.CharField(default="card", max_length=20, verbose_name="결제수단 종류"),
                ),
                (
                    "copy_version",
                    models.CharField(
                        help_text="예: billingConsent@2026-08-10. 문구를 바꾸면 어느 버전에 동의했는지 달라진다",
                        max_length=64,
                        verbose_name="동의 문구 버전",
                    ),
                ),
                ("agreed_terms", models.BooleanField(verbose_name="이용약관 동의")),
                ("agreed_privacy", models.BooleanField(verbose_name="개인정보 수집·이용 동의")),
                (
                    "agreed_recurring",
                    models.BooleanField(verbose_name="정기결제(자동 유료전환) 동의"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="요청 IP"),
                ),
                ("user_agent", models.CharField(blank=True, default="", max_length=300)),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="세션 키 또는 X-Request-ID — 동의 요청을 서버 로그와 이어붙이는 축",
                        max_length=64,
                        verbose_name="세션/요청 식별자",
                    ),
                ),
                (
                    "consented_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        help_text="동의 시점의 구독 행. 구독이 지워져도 동의 기록은 남는다(SET_NULL).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_consents",
                        to="billing.usersubscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "결제 동의 기록",
                "verbose_name_plural": "결제 동의 기록",
                "db_table": "payment_consents",
                "ordering": ["-consented_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "kind", "-consented_at"], name="pconsent_user_kind_idx"
                    )
                ],
            },
        ),
    ]
