# Generated by Django 5.0.1 on 2026-09-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0025_usersubscription_conversion_consent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="trial_kind",
            field=models.CharField(
                blank=True,
                choices=[("card", "카드 등록 체험"), ("auto", "카드 없는 자동 지급 체험")],
                db_index=True,
                default="",
                help_text="card=카드 등록 체험 / auto=카드 없는 자동 지급 체험 / 빈 값=도입 이전. 내구 기록이라 다운그레이드해도 지우지 않는다 (TrialKind docstring 참고).",
                max_length=10,
                verbose_name="체험 시작 경로",
            ),
        ),
    ]
