# Generated by Django 5.0.1 on 2026-02-04 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspace", "0002_workspace_plan_workspace_workspaces_plan_c35e25_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="IGAccountConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "external_account_id",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Instagram Account ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(blank=True, max_length=255, verbose_name="Instagram Username"),
                ),
                (
                    "account_type",
                    models.CharField(blank=True, max_length=50, verbose_name="Account Type"),
                ),
                (
                    "_encrypted_access_token",
                    models.TextField(verbose_name="Encrypted Access Token"),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Token Expires At"),
                ),
                (
                    "scopes",
                    models.JSONField(
                        default=list,
                        help_text="List of granted permissions",
                        verbose_name="OAuth Scopes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "last_verified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Last Verified At"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Last Error Message")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Additional Metadata"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ig_connections",
                        to="workspace.workspace",
                        verbose_name="Workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram Account Connection",
                "verbose_name_plural": "Instagram Account Connections",
                "db_table": "ig_account_connections",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "status"], name="ig_account__workspa_ed1dfc_idx"
                    ),
                    models.Index(
                        fields=["external_account_id"], name="ig_account__externa_3f7456_idx"
                    ),
                    models.Index(fields=["status"], name="ig_account__status_b58777_idx"),
                ],
            },
        ),
    ]
