# Generated by Django 5.0.1 on 2026-02-16 10:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoDMCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "media_id",
                    models.CharField(
                        db_index=True,
                        help_text="댓글을 감지할 Instagram 게시물 ID",
                        max_length=255,
                        verbose_name="Instagram Media ID",
                    ),
                ),
                (
                    "media_url",
                    models.URLField(
                        blank=True, help_text="게시물 URL (참고용)", verbose_name="Media URL"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="캠페인 이름")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "message_template",
                    models.TextField(
                        help_text="댓글 작성자에게 전송될 DM 내용", verbose_name="DM 메시지 템플릿"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "활성"),
                            ("paused", "일시정지"),
                            ("completed", "완료"),
                            ("inactive", "비활성"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "max_sends_per_hour",
                    models.IntegerField(
                        default=200,
                        help_text="스팸 방지를 위한 시간당 발송 제한",
                        verbose_name="시간당 최대 발송 수",
                    ),
                ),
                ("total_sent", models.IntegerField(default=0, verbose_name="총 발송 수")),
                ("total_failed", models.IntegerField(default=0, verbose_name="총 실패 수")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="시작일시"),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True, verbose_name="종료일시")),
                (
                    "ig_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dm_campaigns",
                        to="integrations.igaccountconnection",
                        verbose_name="Instagram Connection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto DM Campaign",
                "verbose_name_plural": "Auto DM Campaigns",
                "db_table": "auto_dm_campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SentDMLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "comment_id",
                    models.CharField(db_index=True, max_length=255, verbose_name="댓글 ID"),
                ),
                ("comment_text", models.TextField(blank=True, verbose_name="댓글 내용")),
                (
                    "recipient_user_id",
                    models.CharField(max_length=255, verbose_name="수신자 Instagram ID"),
                ),
                (
                    "recipient_username",
                    models.CharField(max_length=255, verbose_name="수신자 Username"),
                ),
                ("message_sent", models.TextField(verbose_name="발송된 메시지")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("sent", "발송완료"),
                            ("failed", "발송실패"),
                            ("skipped", "건너뜀"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="에러 메시지")),
                (
                    "error_code",
                    models.CharField(blank=True, max_length=50, verbose_name="에러 코드"),
                ),
                (
                    "webhook_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Webhook 원본 데이터"),
                ),
                (
                    "api_response",
                    models.JSONField(blank=True, default=dict, verbose_name="API 응답 데이터"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="발송일시")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dm_logs",
                        to="integrations.autodmcampaign",
                        verbose_name="캠페인",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sent DM Log",
                "verbose_name_plural": "Sent DM Logs",
                "db_table": "sent_dm_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="autodmcampaign",
            index=models.Index(
                fields=["ig_connection", "status"], name="auto_dm_cam_ig_conn_fe6b75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autodmcampaign",
            index=models.Index(fields=["media_id"], name="auto_dm_cam_media_i_94bd71_idx"),
        ),
        migrations.AddIndex(
            model_name="autodmcampaign",
            index=models.Index(fields=["status"], name="auto_dm_cam_status_8bf155_idx"),
        ),
        migrations.AddIndex(
            model_name="sentdmlog",
            index=models.Index(
                fields=["campaign", "comment_id"], name="sent_dm_log_campaig_a77363_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentdmlog",
            index=models.Index(
                fields=["campaign", "recipient_username"], name="sent_dm_log_campaig_0db907_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentdmlog",
            index=models.Index(fields=["status"], name="sent_dm_log_status_fb3488_idx"),
        ),
        migrations.AddIndex(
            model_name="sentdmlog",
            index=models.Index(fields=["created_at"], name="sent_dm_log_created_17d653_idx"),
        ),
        migrations.AddConstraint(
            model_name="sentdmlog",
            constraint=models.UniqueConstraint(
                fields=("campaign", "comment_id"), name="unique_campaign_comment"
            ),
        ),
    ]
