# Generated by Django 5.0.1 on 2026-02-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_autodmcampaign_sentdmlog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autodmcampaign",
            name="media_url",
            field=models.URLField(
                blank=True, help_text="게시물 URL (참고용)", null=True, verbose_name="Media URL"
            ),
        ),
    ]
