# Generated by Django 5.0.1 on 2026-02-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_alter_autodmcampaign_media_url"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sentdmlog",
            name="unique_campaign_comment",
        ),
    ]
