# Generated by Django 5.0.1 on 2026-02-17 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_remove_sentdmlog_unique_campaign_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpamFilterConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "활성"), ("inactive", "비활성")],
                        default="inactive",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "spam_keywords",
                    models.JSONField(
                        default=list,
                        help_text="검사할 스팸 키워드 목록 (예: ['아이돌', '주소창', '사건'])",
                        verbose_name="스팸 키워드",
                    ),
                ),
                ("block_urls", models.BooleanField(default=True, verbose_name="URL 차단")),
                (
                    "total_spam_detected",
                    models.IntegerField(default=0, verbose_name="총 스팸 감지 수"),
                ),
                ("total_hidden", models.IntegerField(default=0, verbose_name="총 숨김 처리 수")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "ig_connection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spam_filter",
                        to="integrations.igaccountconnection",
                        verbose_name="Instagram Connection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spam Filter Config",
                "verbose_name_plural": "Spam Filter Configs",
                "db_table": "spam_filter_configs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpamCommentLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "comment_id",
                    models.CharField(db_index=True, max_length=255, verbose_name="댓글 ID"),
                ),
                ("comment_text", models.TextField(verbose_name="댓글 내용")),
                (
                    "commenter_user_id",
                    models.CharField(max_length=255, verbose_name="작성자 Instagram ID"),
                ),
                (
                    "commenter_username",
                    models.CharField(max_length=255, verbose_name="작성자 Username"),
                ),
                (
                    "media_id",
                    models.CharField(blank=True, max_length=255, verbose_name="미디어 ID"),
                ),
                (
                    "spam_reasons",
                    models.JSONField(
                        default=list,
                        help_text="스팸으로 판단한 이유 목록 (예: ['contains_url', 'keyword:아이돌'])",
                        verbose_name="스팸 판정 이유",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("detected", "감지됨"),
                            ("hidden", "숨김처리"),
                            ("failed", "처리실패"),
                        ],
                        default="detected",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="에러 메시지")),
                (
                    "webhook_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Webhook 원본 데이터"),
                ),
                (
                    "api_response",
                    models.JSONField(blank=True, default=dict, verbose_name="API 응답 데이터"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="감지일시")),
                (
                    "hidden_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="숨김처리일시"),
                ),
                (
                    "spam_filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spam_logs",
                        to="integrations.spamfilterconfig",
                        verbose_name="스팸 필터",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spam Comment Log",
                "verbose_name_plural": "Spam Comment Logs",
                "db_table": "spam_comment_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="spamfilterconfig",
            index=models.Index(
                fields=["ig_connection", "status"], name="spam_filter_ig_conn_e76a4e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="spamfilterconfig",
            constraint=models.UniqueConstraint(
                fields=("ig_connection",), name="unique_spam_filter_per_ig_connection"
            ),
        ),
        migrations.AddIndex(
            model_name="spamcommentlog",
            index=models.Index(
                fields=["spam_filter", "status"], name="spam_commen_spam_fi_6f84ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spamcommentlog",
            index=models.Index(fields=["comment_id"], name="spam_commen_comment_380cee_idx"),
        ),
        migrations.AddIndex(
            model_name="spamcommentlog",
            index=models.Index(fields=["created_at"], name="spam_commen_created_af2516_idx"),
        ),
    ]
