# Generated by Django 5.0.1 on 2026-02-20 01:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0005_spamfilterconfig_spamcommentlog_and_more"),
        ("workspace", "0002_workspace_plan_workspace_workspaces_plan_c35e25_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="IGOAuthState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("state", models.CharField(db_index=True, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ig_oauth_states",
                        to="workspace.workspace",
                        verbose_name="Workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram OAuth State",
                "verbose_name_plural": "Instagram OAuth States",
                "db_table": "ig_oauth_states",
            },
        ),
    ]
