# Generated by Django 5.0.1 on 2026-05-07 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0008_sentdmlog_status_v3_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="autodmcampaign",
            name="follow_gate_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Opening DM에서 팔로우를 요청하고, 사용자가 gate_trigger_keywords 중 하나로 답장하면 reward DM 자동 발송. Meta 한계로 실제 팔로우 여부는 검증 불가.",
                verbose_name="Follow-gate 사용",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="follow_gate_prompt",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Opening DM에 추가될 follow 요청 문구. 예: '@우리계정 팔로우 후 GO 라고 답장해주세요'",
                verbose_name="Follow-gate 안내 문구",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="gate_trigger_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="이 키워드로 답장 시 gate 통과로 간주. 예: ['GO', 'YES', '네']",
                verbose_name="Gate 통과 키워드",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="keyword_filter",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="비워두면 모든 댓글 매칭. 예: ['info', '가격', '구매']",
                verbose_name="키워드 필터",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="keyword_mode",
            field=models.CharField(
                choices=[
                    ("any", "키워드 중 하나라도 포함"),
                    ("all", "모든 키워드 포함"),
                    ("exact", "댓글 전체 일치"),
                ],
                default="any",
                max_length=10,
                verbose_name="키워드 매칭 방식",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="opening_message_template",
            field=models.TextField(
                blank=True,
                help_text="댓글 작성자에게 발송될 첫 DM (Private Reply via comment_id)",
                verbose_name="Opening DM 템플릿",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="public_reply_enabled",
            field=models.BooleanField(
                default=False,
                help_text="DM 발송 시 댓글에 답글도 함께 게시 (예: 'DM 보내드렸습니다!')",
                verbose_name="공개 답글 게시",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="public_reply_template",
            field=models.TextField(
                blank=True,
                default="",
                help_text="public_reply_enabled=True 일 때 댓글에 게시할 답글 내용",
                verbose_name="공개 답글 템플릿",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="reward_message_template",
            field=models.TextField(
                blank=True,
                default="",
                help_text="follow_gate 통과 후 발송할 본 DM (링크 등 포함)",
                verbose_name="Reward DM 템플릿",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("specific_media", "특정 게시물"),
                    ("any_media", "모든 게시물"),
                    ("next_media", "다음 게시물"),
                ],
                default="specific_media",
                help_text="specific_media: 특정 게시물 / any_media: 모든 게시물 / next_media: 다음 신규 게시물 (자동 attach)",
                max_length=20,
                verbose_name="트리거 종류",
            ),
        ),
        migrations.AddField(
            model_name="sentdmlog",
            name="dm_kind",
            field=models.CharField(
                choices=[
                    ("standalone", "단발 DM (gate 미사용)"),
                    ("opening", "Opening DM (인사/Follow 안내)"),
                    ("reward", "Reward DM (Gate 통과 후 본 DM)"),
                ],
                db_index=True,
                default="standalone",
                max_length=12,
                verbose_name="DM 유형",
            ),
        ),
        migrations.AddField(
            model_name="sentdmlog",
            name="gate_status",
            field=models.CharField(
                choices=[
                    ("none", "미적용"),
                    ("pending", "Gate 답장 대기"),
                    ("passed", "Gate 통과 (reward 발송됨)"),
                    ("expired", "Gate 답장 24h 만료"),
                ],
                db_index=True,
                default="none",
                max_length=10,
                verbose_name="Follow-gate 상태",
            ),
        ),
        migrations.AddField(
            model_name="sentdmlog",
            name="parent_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_logs",
                to="integrations.sentdmlog",
                verbose_name="부모 로그 (gate 통과 시 opening DM)",
            ),
        ),
        migrations.AddField(
            model_name="sentdmlog",
            name="public_reply_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="공개 답글 ID"
            ),
        ),
        migrations.AddField(
            model_name="sentdmlog",
            name="public_reply_posted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="공개 답글 게시 시각"),
        ),
        migrations.AlterField(
            model_name="autodmcampaign",
            name="media_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="specific_media 트리거에서만 사용 (any/next 모드에선 빈 문자열)",
                max_length=255,
                verbose_name="Instagram Media ID",
            ),
        ),
        migrations.AlterField(
            model_name="autodmcampaign",
            name="message_template",
            field=models.TextField(
                blank=True,
                help_text="legacy: opening_message_template 와 동일 의미. 신규 코드는 opening_* 사용.",
                verbose_name="DM 메시지 템플릿 (legacy)",
            ),
        ),
        migrations.AddIndex(
            model_name="autodmcampaign",
            index=models.Index(
                fields=["ig_connection", "trigger_type", "status"],
                name="auto_dm_cam_ig_conn_99a850_idx",
            ),
        ),
    ]
