# Generated by Django 5.0.1 on 2026-05-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0009_autodmcampaign_follow_gate_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="igaccountconnection",
            name="last_polled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="마지막 미디어 폴링 시각"
            ),
        ),
        migrations.AddField(
            model_name="igaccountconnection",
            name="last_seen_media_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="마지막 감지 미디어 timestamp"
            ),
        ),
        migrations.AddField(
            model_name="igaccountconnection",
            name="last_seen_media_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="마지막 감지 미디어 ID"
            ),
        ),
    ]
