# Generated by Django 5.0.1 on 2026-05-11 06:30

from django.db import migrations, models


def backfill_templates(apps, schema_editor):
    """기존 public_reply_template 단일 값을 templates 리스트로 백필"""
    AutoDMCampaign = apps.get_model("integrations", "AutoDMCampaign")
    for c in AutoDMCampaign.objects.exclude(public_reply_template="").iterator():
        existing = c.public_reply_templates or []
        if existing:
            continue
        c.public_reply_templates = [c.public_reply_template]
        c.save(update_fields=["public_reply_templates"])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0011_alter_autodmcampaign_trigger_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="autodmcampaign",
            name="public_reply_batch_pause_seconds",
            field=models.IntegerField(
                default=300,
                help_text="배치 크기 도달 시 다음 답글까지 대기 시간 (Instagram 봇 검사 회피)",
                verbose_name="공개 답글 배치 쿨다운 (초)",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="public_reply_batch_size",
            field=models.IntegerField(
                default=10,
                help_text="이 개수만큼 답글 게시 후 쿨다운(public_reply_batch_pause_seconds) 적용",
                verbose_name="공개 답글 배치 크기",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="public_reply_templates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="댓글마다 무작위로 1개씩 골라 답글로 게시. 봇 검사 회피를 위해 최소 3개 이상 다양한 문구 권장. 예: ['DM 드렸어요!', '확인 부탁드려요 :)', '안내 보내드렸습니다 🎁']",
                verbose_name="공개 답글 템플릿 목록",
            ),
        ),
        migrations.AlterField(
            model_name="autodmcampaign",
            name="follow_gate_enabled",
            field=models.BooleanField(
                default=False,
                help_text="[deprecated] Meta API 한계로 silent 검증 불가능 — 코드 무시됨.",
                verbose_name="Follow-gate 사용 (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="autodmcampaign",
            name="public_reply_template",
            field=models.TextField(
                blank=True,
                default="",
                help_text="[deprecated] 단일 템플릿. 새 캠페인은 public_reply_templates 리스트 사용. 기존 데이터 호환을 위해 유지.",
                verbose_name="공개 답글 템플릿 (legacy 단일)",
            ),
        ),
        migrations.RunPython(backfill_templates, reverse_noop),
    ]
