# Generated by Django 5.0.1 on 2026-05-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0012_autodmcampaign_public_reply_batch_pause_seconds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autodmcampaign",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("specific_media", "특정 게시물"),
                    ("any_media", "모든 게시물"),
                    ("next_media", "다음 게시물"),
                    ("story_reply", "특정 스토리 답장"),
                ],
                default="specific_media",
                help_text="specific_media: 특정 게시물 (media_id 필수) / any_media: 모든 피드 게시물·릴스 / next_media: 캠페인 활성 후 새로 올리는 게시물 1개에만 자동 적용(한번 적용되면 specific_media로 자동 전환됨, 다음 게시물부터는 미적용 — 추가 게시물에도 적용하려면 새 캠페인 생성 필요). 전체 가이드는 GET /api/v1/integrations/auto-dm-campaigns/guide/ 참고.",
                max_length=20,
                verbose_name="트리거 종류",
            ),
        ),
    ]
