# Generated by Django 5.0.1 on 2026-05-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0013_alter_autodmcampaign_trigger_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="autodmcampaign",
            name="follow_gate_button_label",
            field=models.CharField(
                blank=True,
                default="팔로우했어요",
                help_text="quick_reply 버튼 라벨 (Meta 한도 20자). 비우면 '팔로우했어요' 사용.",
                max_length=20,
                verbose_name="Follow-gate 버튼 텍스트",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="follow_gate_retry_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="팔로우 체크가 false 로 돌아왔을 때 발송할 안내. 비우면 기본 문구 사용.\n예: '앗! 팔로우 확인이 안됐어요 😣 프로필에서 팔로우 후 다시 버튼을 눌러주세요!'",
                verbose_name="Follow 미확인 시 재안내 메시지",
            ),
        ),
        migrations.AlterField(
            model_name="autodmcampaign",
            name="follow_gate_enabled",
            field=models.BooleanField(
                default=False,
                help_text="활성화 시 opening DM 에 '팔로우했어요' quick_reply 버튼이 추가되고, 사용자가 버튼 클릭 시 IG Profile API 로 팔로우 여부를 silent 검증한 뒤 reward_message_template 을 발송한다.",
                verbose_name="Follow-gate 사용",
            ),
        ),
        migrations.AlterField(
            model_name="autodmcampaign",
            name="follow_gate_prompt",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Opening DM 본문에 들어갈 follow 요청 문구. 예: '댓글 남겨주셔서 감사해요! 팔로우도 하셨나요? 버튼을 눌러주세요!'",
                verbose_name="Follow-gate 안내 문구",
            ),
        ),
        migrations.AlterField(
            model_name="autodmcampaign",
            name="gate_trigger_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="postback 을 못 받는 구버전 클라이언트 fallback. 이 키워드로 답장 시 gate 통과로 간주. 예: ['GO', 'YES', '네']",
                verbose_name="Gate 통과 키워드 (fallback)",
            ),
        ),
    ]
