# Generated by Django 5.0.1 on 2026-05-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0014_autodmcampaign_follow_gate_button_label_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autodmcampaign",
            name="follow_gate_retry_message",
        ),
    ]
