# Generated by Django 5.0.1 on 2026-05-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0015_remove_autodmcampaign_follow_gate_retry_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="autodmcampaign",
            name="follow_gate_retry_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="팔로우 체크가 false 로 돌아왔을 때 발송할 안내 문구. 비우면 기본 문구 사용.\n예: '앗! 팔로우 확인이 안됐어요 😣 프로필에서 팔로우 후 다시 버튼을 눌러주세요!'",
                verbose_name="Follow 미확인 시 재안내 메시지",
            ),
        ),
    ]
