# Generated by Django 5.0.1 on 2026-06-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0020_autodmcampaign_scheduling"),
    ]

    operations = [
        migrations.AddField(
            model_name="autodmcampaign",
            name="gate_verify_follow",
            field=models.BooleanField(
                default=True,
                help_text="follow_gate_enabled=true 일 때만 의미 있음. true(기본): 버튼 클릭 시 IG Profile API(is_user_follow_business)로 팔로우 여부를 검증한 뒤 통과 시에만 reward 발송 (기존 follow-gate 동작). false: 검증을 건너뛰고 버튼 클릭 즉시 reward 를 발송 (button-only 모드 — 팔로우 확인 없음). follow_gate_enabled=false 면 이 값과 무관하게 게이트 미사용.",
                verbose_name="팔로우 여부 검증",
            ),
        ),
        migrations.AlterField(
            model_name="autodmcampaign",
            name="follow_gate_enabled",
            field=models.BooleanField(
                default=False,
                help_text="활성화 시 opening DM 에 버튼이 추가되고, 사용자가 버튼 클릭 시 reward_message_template 을 발송한다. 버튼 클릭 시 팔로우 검증 여부는 gate_verify_follow 로 제어한다 (true=검증 후 발송 / false=즉시 발송).",
                verbose_name="Follow-gate 사용",
            ),
        ),
    ]
