# Generated by Django 5.0.1 on 2026-06-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0021_autodmcampaign_gate_verify_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="autodmcampaign",
            name="link_button_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="링크 버튼 글자 (Meta 한도 20자). link_button_url 있고 비우면 '자세히 보기'.",
                max_length=20,
                verbose_name="링크 버튼 라벨",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="link_button_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="DM 카드에 붙일 링크 버튼이 여는 URL (http/https). 비우면 버튼 없음.",
                max_length=2048,
                verbose_name="링크 버튼 URL",
            ),
        ),
    ]
