# Generated by Django 5.0.1 on 2026-06-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0023_autodmcampaign_total_unconfirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autodmcampaign",
            name="max_sends_per_hour",
            field=models.IntegerField(
                default=200,
                help_text="캠페인별 사용자 throttle (anti-spam 관행값, 기본 200). Meta 물리 한도는 계정당 750/hr Private Reply 이며 rate_governor 가 계정 단위로 별도 강제한다. 초과 시 드랍하지 않고 다음 시간 윈도우로 defer.",
                verbose_name="시간당 최대 발송 수",
            ),
        ),
    ]
