# Generated by Django 5.0.1 on 2026-06-25 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0024_alter_autodmcampaign_max_sends_per_hour"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeenComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment_id", models.CharField(max_length=255, verbose_name="댓글 ID")),
                (
                    "media_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=255,
                        verbose_name="Media ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("webhook", "웹훅"), ("poll", "폴링")],
                        default="webhook",
                        max_length=10,
                        verbose_name="관측 경로",
                    ),
                ),
                (
                    "triggered",
                    models.BooleanField(
                        default=False,
                        help_text="매칭되어 DM enqueue 했는지 (관측/디버그용)",
                        verbose_name="DM 트리거됨",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="최초 관측 시각"),
                ),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="만료 시각(TTL)")),
                (
                    "ig_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seen_comments",
                        to="integrations.igaccountconnection",
                        verbose_name="Instagram Connection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seen Comment",
                "verbose_name_plural": "Seen Comments",
                "db_table": "seen_comments",
                "indexes": [
                    models.Index(
                        fields=["ig_connection", "media_id"], name="seen_commen_ig_conn_7c57cf_idx"
                    ),
                    models.Index(fields=["expires_at"], name="seen_commen_expires_88f2b7_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="seencomment",
            constraint=models.UniqueConstraint(
                fields=("ig_connection", "comment_id"), name="uq_seen_comment_conn_comment"
            ),
        ),
    ]
