# Generated by Django 5.0.1 on 2026-06-27 03:51

from django.db import migrations, models

# 기존 SentDMLog 의 idempotency_key 를 전역 dedup 레저로 백필.
# 없으면 마이그레이션 직후 "이미 발송된" 댓글이 다시 트리거될 때 create_idempotent 가
# created=True 로 보고 재발송할 수 있다(레저가 비어 있으니 충돌 미발생). created_at 은
# 로그 시각을 그대로 복사해 향후 prune(나이 기준)이 로그와 정렬되게 한다.
# PostgreSQL 전용(ON CONFLICT). 단일 INSERT...SELECT — 런칭 전(소량 데이터)이라 일괄 처리.
BACKFILL_SQL = """
    INSERT INTO dm_dedup_keys (idempotency_key, created_at)
    SELECT idempotency_key, created_at
    FROM sent_dm_logs
    WHERE idempotency_key IS NOT NULL AND idempotency_key <> ''
    ON CONFLICT (idempotency_key) DO NOTHING;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0027_dmaccountblock"),
    ]

    operations = [
        migrations.CreateModel(
            name="DMDedupKey",
            fields=[
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Idempotency Key",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
            ],
            options={
                "verbose_name": "DM Dedup Key",
                "verbose_name_plural": "DM Dedup Keys",
                "db_table": "dm_dedup_keys",
                "indexes": [models.Index(fields=["created_at"], name="dm_dedup_created_idx")],
            },
        ),
        # 테이블 생성 후 실행. reverse 는 CreateModel 이 테이블째 드롭하므로 noop.
        migrations.RunSQL(sql=BACKFILL_SQL, reverse_sql=migrations.RunSQL.noop),
    ]
