# Generated by Django 5.0.1 on 2026-06-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0028_dmdedupkey"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DMDedupKey",
        ),
    ]
