"""WS-2 / §15.8 — EventInbox(webhook_event_inbox)를 received_at 일별 RANGE 파티션으로 전환.

EventInbox 는 transient dedup 장부(36h 지난 마커는 무가치)라 기존 데이터를 보존할 필요가 없어
**DROP + 파티션 테이블 재생성**으로 전환한다(copy/swap 불필요 → 라이브 전환 리스크 최소).
전환 순간 in-flight 중복 웹훅이 잠깐 재처리될 수 있으나 echo/read 재처리는 멱등(status UPDATE)이라 무해.

Django 5.0 은 복합 PK 미지원이라 모델은 id-PK/event_key-unique 그대로 두고(상태 무변경),
DB 테이블만 RunSQL 로 파티션 구조(PK=(id,received_at), UNIQUE=(event_key,received_at))로 만든다.
ORM 은 event_key(get_or_create)·received_at(prune)·id(pk) 모두 파티션 테이블에서 정상 동작.

⚠️ 배포: DDL(테이블 재생성)이라 짧은 유지보수 창에서 적용 권장.
일별 파티션 유지는 integrations.maintain_partitions (beat) 가 담당 — apps/integrations/partition_maintenance.py.
"""

from datetime import date, timedelta

from django.db import migrations

TABLE = "webhook_event_inbox"

# 파티션 테이블 + 인덱스 + DEFAULT 파티션(안전망: 일별 파티션 누락 시에도 INSERT 실패 방지).
FORWARD_DDL = """
DROP TABLE IF EXISTS webhook_event_inbox CASCADE;

CREATE TABLE webhook_event_inbox (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    event_key varchar(255) NOT NULL,
    event_type varchar(32) NOT NULL,
    payload jsonb NOT NULL,
    received_at timestamp with time zone NOT NULL,
    processed_at timestamp with time zone,
    CONSTRAINT webhook_event_inbox_pkey PRIMARY KEY (id, received_at),
    CONSTRAINT webhook_event_inbox_event_key_key UNIQUE (event_key, received_at)
) PARTITION BY RANGE (received_at);

CREATE INDEX webhook_eve_process_idx ON webhook_event_inbox (processed_at);
CREATE INDEX webhook_eve_receive_idx ON webhook_event_inbox (received_at);
CREATE INDEX webhook_event_inbox_event_key_like_idx
    ON webhook_event_inbox (event_key varchar_pattern_ops);

CREATE TABLE webhook_event_inbox_default PARTITION OF webhook_event_inbox DEFAULT;
"""

# 롤백: 비파티션 일반 테이블(0018 구조)로 복원.
REVERSE_DDL = """
DROP TABLE IF EXISTS webhook_event_inbox CASCADE;

CREATE TABLE webhook_event_inbox (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    event_key varchar(255) NOT NULL,
    event_type varchar(32) NOT NULL,
    payload jsonb NOT NULL,
    received_at timestamp with time zone NOT NULL,
    processed_at timestamp with time zone,
    CONSTRAINT webhook_event_inbox_pkey PRIMARY KEY (id),
    CONSTRAINT webhook_event_inbox_event_key_key UNIQUE (event_key)
);

CREATE INDEX webhook_eve_process_idx ON webhook_event_inbox (processed_at);
CREATE INDEX webhook_eve_receive_idx ON webhook_event_inbox (received_at);
CREATE INDEX webhook_event_inbox_event_key_like_idx
    ON webhook_event_inbox (event_key varchar_pattern_ops);
"""


def _create_initial_partitions(apps, schema_editor):
    """전환 직후 즉시 적재되도록 today-1 ~ today+7 일별 파티션을 만들어 둔다(이후는 maintain_partitions)."""
    today = date.today()
    with schema_editor.connection.cursor() as cur:
        for i in range(-1, 8):
            d = today + timedelta(days=i)
            nxt = d + timedelta(days=1)
            name = f"{TABLE}_{d:%Y%m%d}"
            cur.execute(
                f'CREATE TABLE IF NOT EXISTS "{name}" PARTITION OF {TABLE} '
                f"FOR VALUES FROM (%s) TO (%s)",
                [d.isoformat(), nxt.isoformat()],
            )


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0029_drop_dmdedupkey"),
    ]

    operations = [
        migrations.RunSQL(sql=FORWARD_DDL, reverse_sql=REVERSE_DDL),
        migrations.RunPython(_create_initial_partitions, _noop),
    ]
