# Generated by Django 5.0.1 on 2026-07-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0031_spamfilter_llm_decouple"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autodmcampaign",
            name="max_sends_per_hour",
            field=models.IntegerField(
                default=200,
                help_text="(deprecated v4.3 — 더 이상 강제되지 않음) 발송 페이싱은 dm_pacer 가 계정 단위 자동 조절로 대체했다. API 하위호환을 위해 필드만 유지하며 값은 무시된다.",
                verbose_name="시간당 최대 발송 수 (deprecated)",
            ),
        ),
    ]
