# Generated by Django 5.0.1 on 2026-07-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0032_alter_autodmcampaign_max_sends_per_hour"),
    ]

    operations = [
        migrations.AddField(
            model_name="igaccountconnection",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="비활성(False) 계정은 연결/토큰 보존하되 DM·인사이트·스팸필터 등 기능에서 제외됩니다.",
                verbose_name="활성 여부",
            ),
        ),
    ]
