# Generated by Django 5.0.1 on 2026-07-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0033_igaccountconnection_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="autodmcampaign",
            name="recovery_keyword",
            field=models.CharField(
                blank=True,
                default="",
                help_text="비우면 사용자의 아무 DM 이나 복구 재전송을 트리거한다. 값이 있으면 그 키워드가 포함된 DM 만 트리거.",
                max_length=255,
                verbose_name="복구 트리거 키워드 (선택)",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="recovery_reply_enabled",
            field=models.BooleanField(
                default=False,
                help_text="opening 비공개답글이 2534025(비팔로워 채널 미개설)로 실패하면 완전 실패로 두지 않고, 댓글에 '다시 보내드릴게요' 안내 대댓글을 남긴다. 사용자가 이 계정으로 DM 을 보내오면 열린 24h 창으로 opening DM 을 재전송한다.",
                verbose_name="실패 DM 복구 사용",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="recovery_reply_templates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="실패 시 무작위로 1개 골라 댓글에 게시. 봇 검사 회피를 위해 여러 문구 권장. 예: ['DM 전송에 실패했어요 😢 이 계정으로 DM 아무거나 보내주시면 다시 보내드릴게요!']",
                verbose_name="복구 안내 대댓글 템플릿 목록",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="recovery_ttl_seconds",
            field=models.IntegerField(
                default=604800,
                help_text="RECOVERY_PENDING 진입 후 이 시간까지 사용자 DM 이 없으면 RECOVERY_EXPIRED 로 만료. 기본 7일(댓글 비공개답글 창과 동일). 배치/쿨다운은 공개답글 설정을 공유한다.",
                verbose_name="복구 대기 유효기간 (초)",
            ),
        ),
        migrations.AddField(
            model_name="sentdmlog",
            name="recovery_pending_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="복구 대기 진입 시각"),
        ),
        migrations.AddField(
            model_name="sentdmlog",
            name="recovery_reply_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="복구 안내 답글 ID"
            ),
        ),
        migrations.AlterField(
            model_name="sentdmlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "큐 대기"),
                    ("submitting", "API 호출 중"),
                    ("accepted", "Meta 접수됨"),
                    ("delivered", "도착 확인"),
                    ("read", "읽음 확인"),
                    ("pending", "대기중(legacy)"),
                    ("sent", "발송완료(legacy)"),
                    ("failed", "발송실패(legacy)"),
                    ("skipped", "건너뜀"),
                    ("failed_token", "토큰 만료/세션 무효"),
                    ("failed_window", "24h 윈도우 만료"),
                    ("failed_param", "파라미터 오류"),
                    ("rate_limited", "Meta 응답 대기 (지연)"),
                    ("failed_no_trace", "도착 미확인 (자가 점검 필요)"),
                    ("failed_api", "API 실패(legacy)"),
                    ("recovery_pending", "복구 대기 (안내 답글 게시, 사용자 DM 대기)"),
                    ("recovery_delivered", "복구 재전송 성공"),
                    ("recovery_expired", "복구 대기 만료 (사용자 무응답)"),
                ],
                default="queued",
                max_length=20,
                verbose_name="상태",
            ),
        ),
    ]
