# Generated by Django 5.0.1 on 2026-07-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0035_alter_autodmcampaign_recovery_reply_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="autodmcampaign",
            name="follow_gate_prompt_templates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="게이트 오프닝 DM 변형 목록. 비어있지 않으면 발송 시마다 무작위로 1개 선택 (스팸판정 회피). 비우면 follow_gate_prompt 단일값 사용. diversify-opening API 로 생성한 변형을 여기에 저장한다.",
                verbose_name="Follow-gate 안내 문구 변형 목록 (회전)",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="opening_message_templates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="비게이트 오프닝 DM 변형 목록. 비어있지 않으면 발송 시마다 무작위로 1개 선택 (동일 메시지 대량발송 스팸판정 회피). 비우면 opening_message_template 단일값 사용. diversify-opening API 로 생성한 변형을 여기에 저장한다.",
                verbose_name="Opening DM 변형 목록 (회전)",
            ),
        ),
    ]
