# Generated by Django 5.0.1 on 2026-07-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0036_autodmcampaign_follow_gate_prompt_templates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autodmcampaign",
            name="recovery_keyword",
            field=models.CharField(
                blank=True,
                default="",
                help_text="(deprecated v2 — 인바운드 DM 트리거 폐기로 더 이상 사용되지 않음. API 하위호환을 위해 필드만 유지하며 값은 무시된다.)",
                max_length=255,
                verbose_name="복구 트리거 키워드 (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="autodmcampaign",
            name="recovery_reply_enabled",
            field=models.BooleanField(
                default=True,
                help_text="opening 비공개답글이 2534025(비팔로워 채널 미개설)로 **확정** 실패하면 완전 실패로 두지 않고, 댓글에 'DM이 숨겨진 요청/스팸함으로 갔어요 — 수락 후 다시 댓글 달아주세요' 안내 대댓글을 남긴다. 사용자가 요청을 수락하고 다시 댓글을 달면 일반 발송 경로로 재발송되며, 성공 시 이전 실패 건은 자동으로 성공 처리된다. **프로 전용**(dm_recovery 기능) — 미보유 플랜에서는 켜져 있어도 동작하지 않고 해당 DM 은 일반 실패로 종결된다.",
                verbose_name="실패 DM 복구 사용",
            ),
        ),
        migrations.AlterField(
            model_name="autodmcampaign",
            name="recovery_reply_templates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="실패 시 무작위로 1개 골라 댓글에 게시. 봇 검사 회피를 위해 여러 문구 권장. 비우면 서버 조합기가 매번 새 문구 생성. 예: ['DM이 숨겨진 요청함으로 갔어요 🥲 수락하시고 다시 댓글 남겨주시면 바로 보내드릴게요!']",
                verbose_name="복구 안내 대댓글 템플릿 목록",
            ),
        ),
        migrations.AlterField(
            model_name="autodmcampaign",
            name="recovery_ttl_seconds",
            field=models.IntegerField(
                default=604800,
                help_text="RECOVERY_PENDING 진입 후 이 시간까지 같은 사용자의 재댓글 발송 성공이 없으면 RECOVERY_EXPIRED 로 만료(완전 실패 정산). 기본 7일(댓글 비공개답글 창과 동일). 배치/쿨다운은 공개답글 설정을 공유한다.",
                verbose_name="복구 대기 유효기간 (초)",
            ),
        ),
        migrations.AlterField(
            model_name="sentdmlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "큐 대기"),
                    ("submitting", "API 호출 중"),
                    ("accepted", "Meta 접수됨"),
                    ("delivered", "도착 확인"),
                    ("read", "읽음 확인"),
                    ("pending", "대기중(legacy)"),
                    ("sent", "발송완료(legacy)"),
                    ("failed", "발송실패(legacy)"),
                    ("skipped", "건너뜀"),
                    ("failed_token", "토큰 만료/세션 무효"),
                    ("failed_window", "24h 윈도우 만료"),
                    ("failed_param", "파라미터 오류"),
                    ("rate_limited", "Meta 응답 대기 (지연)"),
                    ("failed_no_trace", "도착 미확인 (자가 점검 필요)"),
                    ("failed_api", "API 실패(legacy)"),
                    ("recovery_pending", "복구 대기 (안내 답글 게시, 수락·재댓글 대기)"),
                    ("recovery_delivered", "복구 재전송 성공"),
                    ("recovery_expired", "복구 대기 만료 (수락·재댓글 없음)"),
                ],
                default="queued",
                max_length=20,
                verbose_name="상태",
            ),
        ),
    ]
