# Generated by Django 5.0.1 on 2026-07-20 10:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0042_remove_autodmcampaign_max_sends_per_hour"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DMMigrationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "대기"),
                            ("running", "분석 중"),
                            ("paused_rate_limited", "레이트리밋 대기(자동 재개)"),
                            ("ready", "완료"),
                            ("partial", "부분 완료"),
                            ("failed", "실패"),
                            ("canceled", "취소됨"),
                        ],
                        default="queued",
                        max_length=24,
                        verbose_name="상태",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("queued", "대기"),
                            ("collecting_media", "게시물 수집 중"),
                            ("collecting_comments", "댓글 수집 중"),
                            ("classifying_posts", "게시물 분류 중"),
                            ("collecting_dm_conversations", "DM 기록 수집 중"),
                            ("clustering_dm_templates", "DM 패턴 분석 중"),
                            ("matching_campaigns", "게시물-DM 매칭 중"),
                            ("generating_drafts", "캠페인 초안 생성 중"),
                            ("completed", "완료"),
                        ],
                        default="queued",
                        max_length=32,
                        verbose_name="진행 단계",
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0~100", verbose_name="진행률 (%)"
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="진행 메시지"
                    ),
                ),
                (
                    "media_limit",
                    models.IntegerField(
                        default=50,
                        help_text="최근 게시물 몇 개까지 분석할지 (10~100).",
                        validators=[django.core.validators.MinValueValidator(10)],
                        verbose_name="분석 게시물 수",
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        default="deepseek",
                        help_text="AiJob.LlmModel 값",
                        max_length=20,
                        verbose_name="LLM 모델",
                    ),
                ),
                ("media_scanned", models.IntegerField(default=0)),
                ("comments_collected", models.IntegerField(default=0)),
                ("conversations_scanned", models.IntegerField(default=0)),
                ("dm_messages_collected", models.IntegerField(default=0)),
                ("templates_found", models.IntegerField(default=0)),
                ("candidates_created", models.IntegerField(default=0)),
                (
                    "api_budget_state",
                    models.JSONField(blank=True, default=dict, verbose_name="API 예산 상태"),
                ),
                ("llm_calls", models.IntegerField(default=0)),
                ("llm_tokens_used", models.IntegerField(default=0)),
                (
                    "rate_limit_pauses",
                    models.IntegerField(
                        default=0,
                        help_text="3회 초과 시 partial 종결",
                        verbose_name="레이트리밋 pause 횟수",
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="에러 코드"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="에러 메시지"),
                ),
                (
                    "cancel_requested",
                    models.BooleanField(default=False, verbose_name="취소 요청됨"),
                ),
                (
                    "resume_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="paused_rate_limited 시 설정",
                        null=True,
                        verbose_name="재개 예정 시각",
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Celery Task ID"
                    ),
                ),
                (
                    "stage_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="media 목록·media별 댓글(캡 250·200자 절단)·발신 DM(캡 500)·판정/클러스터/매칭 결과. 재개 가능하도록 단계키별로 누적된다. purge_dm_migration_raw 가 {} 로 파기.",
                        verbose_name="단계별 체크포인트(원본 포함 — 7일 후 파기)",
                    ),
                ),
                (
                    "raw_expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="원본 파기 예정 시각(완료+7일)",
                    ),
                ),
                (
                    "raw_purged_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="원본 파기 완료 시각"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="실행 시작"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="실행 종료"),
                ),
                (
                    "ig_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="migration_jobs",
                        to="integrations.igaccountconnection",
                        verbose_name="Instagram Connection",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dm_migration_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="요청자",
                    ),
                ),
            ],
            options={
                "verbose_name": "DM Migration Job",
                "verbose_name_plural": "DM Migration Jobs",
                "db_table": "dm_migration_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DMCampaignCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("detected", "감지됨"),
                            ("applied", "적용됨(초안 생성)"),
                            ("dismissed", "무시됨"),
                        ],
                        default="detected",
                        max_length=16,
                        verbose_name="상태",
                    ),
                ),
                (
                    "band",
                    models.CharField(
                        choices=[
                            ("auto_draft", "자동 초안(강한 후보)"),
                            ("needs_review", "검수 필요"),
                            ("template_only", "템플릿만(게시물 미상)"),
                            ("excluded", "제외"),
                        ],
                        default="needs_review",
                        max_length=16,
                        verbose_name="매칭 밴드",
                    ),
                ),
                (
                    "media_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=255,
                        verbose_name="게시물 ID",
                    ),
                ),
                (
                    "media_permalink",
                    models.URLField(blank=True, default="", verbose_name="게시물 URL"),
                ),
                (
                    "media_caption_excerpt",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="캡션 발췌"
                    ),
                ),
                (
                    "media_timestamp",
                    models.DateTimeField(blank=True, null=True, verbose_name="게시물 작성 시각"),
                ),
                (
                    "suggested_keywords",
                    models.JSONField(blank=True, default=list, verbose_name="추천 트리거 키워드"),
                ),
                (
                    "suggested_keyword_mode",
                    models.CharField(
                        choices=[
                            ("any", "키워드 중 하나라도 포함"),
                            ("all", "모든 키워드 포함"),
                            ("exact", "댓글 전체 일치"),
                        ],
                        default="any",
                        max_length=10,
                        verbose_name="키워드 매칭 방식",
                    ),
                ),
                ("confidence", models.FloatField(default=0.0, verbose_name="신뢰도 (0~1)")),
                (
                    "draft_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="초안 캠페인명"
                    ),
                ),
                (
                    "draft_description",
                    models.TextField(blank=True, default="", verbose_name="초안 설명"),
                ),
                (
                    "draft_opening_message",
                    models.TextField(blank=True, default="", verbose_name="초안 첫 DM"),
                ),
                (
                    "draft_public_reply_templates",
                    models.JSONField(blank=True, default=list, verbose_name="초안 공개답글 목록"),
                ),
                (
                    "follow_up_candidates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"text", "confidence", "source_template_id", "cluster_size"}]',
                        verbose_name="후속 DM 후보",
                    ),
                ),
                (
                    "matched_template",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"template_id","cluster_size","variable_slots","first_sent_at","last_sent_at"}',
                        verbose_name="매칭 템플릿 메타",
                    ),
                ),
                (
                    "evidence_aggregates",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="matched/total 댓글 수, keyword_hit_counts, account_replied_publicly, dm_burst_overlap_ratio, time_window, has_existing_campaign, own_sends_excluded.",
                        verbose_name="근거 집계(영구 보존)",
                    ),
                ),
                (
                    "evidence_raw",
                    models.JSONField(
                        blank=True,
                        help_text="sample_comments(≤5)·sample_outbound_dms(≤3)·template_representative_text.",
                        null=True,
                        verbose_name="근거 원본(7일 후 파기 → None)",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="적용 시각"),
                ),
                (
                    "dismissed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="무시 시각"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applied_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="migration_candidates",
                        to="integrations.autodmcampaign",
                        verbose_name="생성된 캠페인",
                    ),
                ),
                (
                    "ig_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="migration_candidates",
                        to="integrations.igaccountconnection",
                        verbose_name="Instagram Connection",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="integrations.dmmigrationjob",
                        verbose_name="마이그레이션 잡",
                    ),
                ),
            ],
            options={
                "verbose_name": "DM Campaign Candidate",
                "verbose_name_plural": "DM Campaign Candidates",
                "db_table": "dm_campaign_candidates",
                "ordering": ["-confidence", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dmmigrationjob",
            index=models.Index(
                fields=["ig_connection", "status"], name="dm_migratio_ig_conn_5ca4a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dmmigrationjob",
            index=models.Index(
                fields=["status", "raw_expires_at"], name="dm_migratio_status_9aeba3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dmmigrationjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["queued", "running", "paused_rate_limited"])),
                fields=("ig_connection",),
                name="uniq_nonterminal_migration_per_connection",
            ),
        ),
        migrations.AddIndex(
            model_name="dmcampaigncandidate",
            index=models.Index(fields=["job", "status"], name="dm_campaign_job_id_7bf1db_idx"),
        ),
        migrations.AddIndex(
            model_name="dmcampaigncandidate",
            index=models.Index(
                fields=["ig_connection", "status"], name="dm_campaign_ig_conn_6d6180_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dmcampaigncandidate",
            index=models.Index(fields=["media_id"], name="dm_campaign_media_i_d8bde6_idx"),
        ),
        migrations.AddConstraint(
            model_name="dmcampaigncandidate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("media_id", ""), _negated=True),
                fields=("job", "media_id"),
                name="uniq_candidate_per_job_media",
            ),
        ),
    ]
