# Generated by Django 5.0.1 on 2026-07-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0043_dmmigrationjob_dmcampaigncandidate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dmmigrationjob",
            name="stage",
            field=models.CharField(
                choices=[
                    ("queued", "대기"),
                    ("collecting_media", "게시물 수집 중"),
                    ("collecting_comments", "댓글 수집 중"),
                    ("classifying_posts", "게시물 분류 중"),
                    ("collecting_targeted_dms", "타겟 DM 복원 중"),
                    ("collecting_dm_conversations", "DM 기록 수집 중"),
                    ("clustering_dm_templates", "DM 패턴 분석 중"),
                    ("matching_campaigns", "게시물-DM 매칭 중"),
                    ("generating_drafts", "캠페인 초안 생성 중"),
                    ("completed", "완료"),
                ],
                default="queued",
                max_length=32,
                verbose_name="진행 단계",
            ),
        ),
    ]
