# Generated by Django 5.0.1 on 2026-07-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0045_spamfilter_reset_seeded_default_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="igaccountconnection",
            name="biography",
            field=models.TextField(blank=True, default="", verbose_name="프로필 소개글"),
        ),
        migrations.AddField(
            model_name="igaccountconnection",
            name="followers_count",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="팔로워 수"),
        ),
        migrations.AddField(
            model_name="igaccountconnection",
            name="follows_count",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="팔로잉 수"),
        ),
        migrations.AddField(
            model_name="igaccountconnection",
            name="media_count",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="게시물 수"),
        ),
        migrations.AddField(
            model_name="igaccountconnection",
            name="stats_synced_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="프로필 통계 갱신 시각"),
        ),
    ]
