# Generated by Django 5.0.1 on 2026-08-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0047_igoauthstate_return_to_and_opener_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="autodmcampaign",
            name="thumbnail_source_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="다운로드에 사용한 IG CDN URL (dedup·디버그용). 만료되므로 표시에 쓰지 말 것.",
                verbose_name="썸네일 원본 CDN URL",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="thumbnail_sync_attempts",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="성공 시 0 으로 리셋. 삭제된 게시물처럼 영구 실패하는 건이 스위퍼 슬롯을 독점하지 않도록 상한(THUMBNAIL_MAX_SYNC_ATTEMPTS)을 넘으면 스위퍼가 제외한다.",
                verbose_name="썸네일 동기화 연속 실패 횟수",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="thumbnail_sync_error",
            field=models.TextField(
                blank=True, default="", verbose_name="썸네일 동기화 마지막 에러"
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="thumbnail_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="썸네일 마지막 동기화 시각"
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="thumbnail_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="우리 스토리지(R2/로컬)에 재호스팅한 게시물 썸네일의 영구 URL. 만료되지 않고 게시물이 삭제된 뒤에도 남는다. 비어 있으면 아직 미동기화(또는 동기화 실패).",
                verbose_name="게시물 썸네일 URL (우리 스토리지)",
            ),
        ),
        migrations.AlterField(
            model_name="autodmcampaign",
            name="media_url",
            field=models.URLField(
                blank=True,
                help_text="게시물 영구 링크(https://www.instagram.com/p/{shortcode}/). 생성/게시물 변경 직후 backfill_campaign_media_permalink 가 Graph 에서 조회해 채운다(사용자 자유 입력도 허용). ⚠️ 이미지가 아니다 — 썸네일 표시에는 thumbnail_url 을 쓸 것.",
                max_length=512,
                null=True,
                verbose_name="게시물 permalink",
            ),
        ),
    ]
