# Generated by Django 5.0.1 on 2026-08-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0049_autodmcampaign_backfill_existing_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="autodmcampaign",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("dm_migration", "다른 서비스에서 불러옴")],
                db_index=True,
                default="",
                help_text="빈 문자열 = 사용자가 직접 만든 캠페인.",
                max_length=20,
                verbose_name="생성 출처",
            ),
        ),
        migrations.AddField(
            model_name="dmcampaigncandidate",
            name="confirm_required",
            field=models.BooleanField(
                default=False,
                help_text="지지 표본이 적어 링크 확인을 받아야 하는 후보.",
                verbose_name="사용자 확인 필요",
            ),
        ),
        migrations.AddField(
            model_name="dmcampaigncandidate",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="사용자 확인 시각"),
        ),
        migrations.AddField(
            model_name="dmcampaigncandidate",
            name="confirmed_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="비어 있으면 offer_url 을 그대로 쓴다.",
                max_length=1000,
                verbose_name="사용자가 확정/수정한 링크",
            ),
        ),
        migrations.AddField(
            model_name="dmcampaigncandidate",
            name="gate_button_label",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="게이트 버튼 문구(복원)"
            ),
        ),
        migrations.AddField(
            model_name="dmcampaigncandidate",
            name="gate_detected",
            field=models.BooleanField(
                default=False,
                help_text="cta.type=postback 로 판별",
                verbose_name="팔로우 확인 단계 사용",
            ),
        ),
        migrations.AddField(
            model_name="dmcampaigncandidate",
            name="gate_message",
            field=models.TextField(blank=True, default="", verbose_name="게이트 문구(복원)"),
        ),
        migrations.AddField(
            model_name="dmcampaigncandidate",
            name="offer_button_label",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="오퍼 버튼 문구(복원)"
            ),
        ),
        migrations.AddField(
            model_name="dmcampaigncandidate",
            name="offer_url",
            field=models.URLField(
                blank=True, default="", max_length=1000, verbose_name="오퍼 링크(복원)"
            ),
        ),
        migrations.AddField(
            model_name="dmcampaigncandidate",
            name="support_hits",
            field=models.IntegerField(
                default=0, help_text="지지비율의 분자", verbose_name="같은 문구를 받은 댓글러 수"
            ),
        ),
        migrations.AddField(
            model_name="dmcampaigncandidate",
            name="support_probed",
            field=models.IntegerField(
                default=0, help_text="지지비율의 분모", verbose_name="조회한 댓글러 수"
            ),
        ),
        migrations.AddField(
            model_name="dmcampaigncandidate",
            name="support_score",
            field=models.FloatField(
                default=0.0,
                help_text="표본이 작으면 자동 강등된다. 1/2→0.09 · 3/3→0.44 · 10/10→0.72.",
                verbose_name="지지 신뢰하한(Wilson)",
            ),
        ),
        migrations.AddField(
            model_name="dmcampaigncandidate",
            name="transfer_drops",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='[{"code":"attachment_image","count":3}] — 프론트 i18n 키와 1:1.',
                verbose_name="이전 못 하는 항목",
            ),
        ),
        migrations.AddField(
            model_name="dmmigrationjob",
            name="estimate_detail",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="{media_total, media_with_comments, per_post_seconds, workers}",
                verbose_name="예상 산출 근거",
            ),
        ),
        migrations.AddField(
            model_name="dmmigrationjob",
            name="estimated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="예상 산출 완료 시각"),
        ),
        migrations.AddField(
            model_name="dmmigrationjob",
            name="estimated_seconds",
            field=models.IntegerField(
                blank=True,
                help_text="1단계에서 산출. 게시물 수 × 게시물당 실측 단가.",
                null=True,
                verbose_name="예상 소요(초)",
            ),
        ),
        migrations.AddField(
            model_name="dmmigrationjob",
            name="trigger_source",
            field=models.CharField(
                choices=[("manual", "사용자 요청"), ("auto_connect", "연동 직후 자동")],
                default="manual",
                help_text="auto_connect = IG 연동 완료 시 백그라운드 선작업(캐시 목적).",
                max_length=16,
                verbose_name="실행 계기",
            ),
        ),
        migrations.AddField(
            model_name="igaccountconnection",
            name="dm_migration_conflict_ack_at",
            field=models.DateTimeField(
                blank=True,
                help_text="불러온 캠페인을 처음 켤 때 1회 확인. 중복 발송 경고용.",
                null=True,
                verbose_name="타 서비스 연동 해제 확인 시각",
            ),
        ),
        migrations.AddField(
            model_name="igaccountconnection",
            name="dm_migration_prompt_answer",
            field=models.CharField(
                blank=True,
                choices=[("used", "다른 서비스 써봤음"), ("first_time", "처음임")],
                default="",
                help_text="연동 직후 '다른 서비스로 자동 DM 보낸 적 있으세요?' 답.",
                max_length=16,
                verbose_name="이전 설문 답변",
            ),
        ),
        migrations.AddField(
            model_name="igaccountconnection",
            name="dm_migration_prompt_answered_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="이전 설문 응답 시각"),
        ),
        migrations.AlterField(
            model_name="dmmigrationjob",
            name="stage",
            field=models.CharField(
                choices=[
                    ("queued", "대기"),
                    ("estimating", "예상 시간 계산 중"),
                    ("collecting_media", "게시물 수집 중"),
                    ("collecting_comments", "댓글 수집 중"),
                    ("classifying_posts", "게시물 분류 중"),
                    ("collecting_targeted_dms", "타겟 DM 복원 중"),
                    ("collecting_dm_conversations", "DM 기록 수집 중"),
                    ("clustering_dm_templates", "DM 패턴 분석 중"),
                    ("matching_campaigns", "게시물-DM 매칭 중"),
                    ("generating_drafts", "캠페인 초안 생성 중"),
                    ("completed", "완료"),
                ],
                default="queued",
                max_length=32,
                verbose_name="진행 단계",
            ),
        ),
    ]
