# Generated by Django 5.0.1 on 2026-08-17 14:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0050_dm_migration_precision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dmmigrationjob",
            name="media_limit",
            field=models.IntegerField(
                default=50,
                help_text="최근 게시물 몇 개까지 분석할지. Graph 호출 예산이 이 값에 비례해 정해진다 (dm_migration.collect.caps_for). 전수 복원은 계정 게시물 수를 그대로 넣는다.",
                validators=[django.core.validators.MinValueValidator(10)],
                verbose_name="분석 게시물 수",
            ),
        ),
        migrations.CreateModel(
            name="IGPostAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("media_id", models.CharField(max_length=64, verbose_name="게시물 ID")),
                (
                    "media_timestamp",
                    models.DateTimeField(blank=True, null=True, verbose_name="게시 시각"),
                ),
                ("permalink", models.CharField(blank=True, default="", max_length=500)),
                (
                    "rules_version",
                    models.PositiveIntegerField(default=1, verbose_name="판정 규칙 버전"),
                ),
                (
                    "comments_count",
                    models.IntegerField(default=0, verbose_name="분석 당시 댓글 수"),
                ),
                ("analyzed_at", models.DateTimeField(auto_now=True, verbose_name="분석 시각")),
                ("grade", models.CharField(default="", max_length=20, verbose_name="등급")),
                ("content_score", models.FloatField(default=0.0, verbose_name="글·댓글 판정 점수")),
                (
                    "content_reasons",
                    models.JSONField(blank=True, default=list, verbose_name="걸린 신호"),
                ),
                (
                    "trigger",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="트리거 낱말"
                    ),
                ),
                ("probed", models.IntegerField(default=0, verbose_name="조회 인원")),
                (
                    "support_hits",
                    models.IntegerField(default=0, verbose_name="같은 문구 수신 인원"),
                ),
                (
                    "gap_median",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="댓글→DM 간격 중앙값(초)"
                    ),
                ),
                (
                    "auto_hits",
                    models.IntegerField(default=0, verbose_name="자동발송 창 안 수신 인원"),
                ),
                (
                    "has_offer_url",
                    models.BooleanField(default=False, verbose_name="오퍼 링크 확보"),
                ),
                (
                    "dug_all_comments",
                    models.BooleanField(default=False, verbose_name="첫 댓글까지 팠나"),
                ),
                (
                    "dug_conversations",
                    models.BooleanField(default=False, verbose_name="대화 처음까지 팠나"),
                ),
                (
                    "probe_pool",
                    models.JSONField(
                        blank=True, default=list, verbose_name="조회 대상 풀(id·시각)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ig_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_analyses",
                        to="integrations.igaccountconnection",
                        verbose_name="IG 연결",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시물 DM 분석 캐시",
                "verbose_name_plural": "게시물 DM 분석 캐시",
                "db_table": "ig_post_analysis",
                "ordering": ["-analyzed_at"],
                "indexes": [
                    models.Index(
                        fields=["ig_connection", "rules_version"],
                        name="ig_post_ana_ig_conn_40db90_idx",
                    ),
                    models.Index(
                        fields=["ig_connection", "grade"], name="ig_post_ana_ig_conn_961311_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="igpostanalysis",
            constraint=models.UniqueConstraint(
                fields=("ig_connection", "media_id"), name="uniq_post_analysis_per_media"
            ),
        ),
    ]
