# Generated by Django 5.0.1 on 2026-08-31 07:41
#
# 동일 수신자 쿨다운의 '게시물 범위' 판정용 컬럼. 상수 default('') 라 PostgreSQL 11+ 에서는
# 메타데이터만 바뀌는 즉시 ADD COLUMN 이다(테이블 재작성/장기 락 없음) — sent_dm_logs 가
# 커도 prod 배포에서 블로킹되지 않는다. 백필 불필요: 판정 창이 5분이라 배포 후 몇 분 안에
# 창 안 모든 행이 값을 갖는다. 그 전까지는 media_id="" → 완화 없이 종전 동작(창 안 1통).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0051_post_analysis_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentdmlog",
            name="media_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="트리거 게시물 ID"
            ),
        ),
    ]
