# Generated by Django 5.0.1 on 2026-08-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0052_sentdmlog_media_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="igaccountconnection",
            name="reconnect_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="token_invalidated(비밀번호 변경·보안 세션 초기화) / account_checkpoint(인스타그램에서 본인확인 필요) / app_removed(앱 권한 회수) / reconnect_required(기타). 빈 값 = 정상.",
                max_length=32,
                verbose_name="재연동 필요 사유",
            ),
        ),
        migrations.AddField(
            model_name="igaccountconnection",
            name="token_dead_first_seen_at",
            field=models.DateTimeField(
                blank=True,
                help_text="첫 스트라이크 시각. '언제부터 죽어있나' 진단용.",
                null=True,
                verbose_name="토큰 사망 최초 감지 시각",
            ),
        ),
        migrations.AddField(
            model_name="igaccountconnection",
            name="token_dead_strikes",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="임계 도달 시 status=error 확정. 토큰이 살아있으면 0 으로 초기화.",
                verbose_name="토큰 사망 연속 확인 횟수",
            ),
        ),
    ]
