# Generated by Django 5.0.1 on 2026-09-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0053_igaccountconnection_reconnect_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="autodmcampaign",
            name="auto_paused_at",
            field=models.DateTimeField(
                blank=True,
                help_text="게시물이 인스타그램에 의해 제한돼 시스템이 캠페인을 멈춘 시각. 사용자가 직접 재개하면 비운다.",
                null=True,
                verbose_name="시스템 자동 정지 시각",
            ),
        ),
        migrations.AddField(
            model_name="autodmcampaign",
            name="auto_paused_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="머신 키. 현재는 'post_restricted' 하나 — apps.integrations.dm_user_reasons 의 U_POST_RESTRICTED 와 같은 네임스페이스.",
                max_length=50,
                verbose_name="시스템 자동 정지 사유",
            ),
        ),
    ]
