# Generated by Django 5.0.1 on 2026-09-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0054_autodmcampaign_auto_paused_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="igaccountconnection",
            name="latest_media_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="최신 게시물 게시 시각"
            ),
        ),
        migrations.AddField(
            model_name="igaccountconnection",
            name="latest_media_checked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="최신 게시물 확인 시각"),
        ),
        migrations.AddField(
            model_name="igaccountconnection",
            name="latest_media_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="최신 게시물 ID"
            ),
        ),
        migrations.AddField(
            model_name="igaccountconnection",
            name="latest_media_permalink",
            field=models.TextField(blank=True, default="", verbose_name="최신 게시물 링크"),
        ),
        migrations.AddField(
            model_name="igaccountconnection",
            name="webhook_checked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="실시간 수신 확인 시각"),
        ),
        migrations.AddField(
            model_name="igaccountconnection",
            name="webhook_healthy",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="None=미확인 / True=정상 / False=구독 꺼짐(재구독 실패). 홈 알림 판정용.",
                null=True,
                verbose_name="실시간 수신 정상 여부",
            ),
        ),
    ]
