# Generated by Django 5.0.1 on 2026-09-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0055_igaccountconnection_latest_media_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dmaccountblock",
            name="last_trip_campaign_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="마지막 트립을 유발한 캠페인 id"
            ),
        ),
        migrations.AddField(
            model_name="dmaccountblock",
            name="last_trip_error",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="마지막 트립 당시 Meta 오류 요약",
            ),
        ),
        migrations.AddField(
            model_name="dmaccountblock",
            name="last_trip_log_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="마지막 트립을 유발한 SentDMLog id"
            ),
        ),
        migrations.AddField(
            model_name="dmaccountblock",
            name="total_trips",
            field=models.IntegerField(
                default=0,
                help_text="이 계정에서 Action Block 이 발생한 총 횟수. level 은 해제 시 0 으로 내려가므로 '재발 횟수' 표시에는 이 값을 쓴다(감사용 · 절대 감소하지 않음).",
                verbose_name="누적 트립 횟수",
            ),
        ),
    ]
