# Generated by Django 5.0.1 on 2026-05-07 09:01

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspace", "0002_workspace_plan_workspace_workspaces_plan_c35e25_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeQuotaUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("day", models.DateField(db_index=True, default=datetime.date.today, unique=True)),
                ("units_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "youtube_quota_usage",
                "ordering": ["-day"],
            },
        ),
        migrations.CreateModel(
            name="YouTubeAccountConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "external_account_id",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="YouTube channel ID"
                    ),
                ),
                ("channel_title", models.CharField(blank=True, default="", max_length=255)),
                ("channel_thumbnail_url", models.URLField(blank=True, default="")),
                (
                    "google_user_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Google account ``sub`` claim (per-app pseudonymous identifier).",
                        max_length=255,
                    ),
                ),
                (
                    "google_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Authenticated Google email (only for display; do not authorize on this).",
                        max_length=254,
                    ),
                ),
                (
                    "_encrypted_access_token",
                    models.TextField(verbose_name="Encrypted Access Token"),
                ),
                (
                    "_encrypted_refresh_token",
                    models.TextField(
                        blank=True, default="", verbose_name="Encrypted Refresh Token"
                    ),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("scopes", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_connections",
                        to="workspace.workspace",
                        verbose_name="Workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "YouTube Account Connection",
                "verbose_name_plural": "YouTube Account Connections",
                "db_table": "youtube_account_connections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="YouTubeOAuthState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("state", models.CharField(db_index=True, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_oauth_states",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "youtube_oauth_states",
            },
        ),
        migrations.CreateModel(
            name="YouTubeVideoPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("tags", models.JSONField(blank=True, default=list)),
                ("category_id", models.CharField(default="22", max_length=20)),
                (
                    "privacy_status",
                    models.CharField(
                        choices=[
                            ("private", "비공개"),
                            ("unlisted", "일부 공개"),
                            ("public", "공개"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("made_for_kids", models.BooleanField(default=False)),
                (
                    "video_file_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="서버 측 영상 파일 경로 (MEDIA_ROOT 기반 또는 절대경로)",
                        max_length=500,
                    ),
                ),
                ("video_size_bytes", models.BigIntegerField(default=0)),
                (
                    "youtube_video_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "큐 대기"),
                            ("uploading", "업로드 중"),
                            ("processing", "YouTube 처리 중"),
                            ("published", "발행 완료"),
                            ("failed", "발행 실패"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("fail_reason", models.TextField(blank=True, default="")),
                ("api_response", models.JSONField(blank=True, default=dict)),
                (
                    "quota_units_consumed",
                    models.IntegerField(
                        default=0,
                        help_text="이번 발행이 소비한 quota units (videos.insert 성공 시 1600)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_posts",
                        to="youtube.youtubeaccountconnection",
                    ),
                ),
            ],
            options={
                "db_table": "youtube_video_posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="youtubeaccountconnection",
            index=models.Index(
                fields=["workspace", "status"], name="youtube_acc_workspa_8a2abe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="youtubeaccountconnection",
            index=models.Index(
                fields=["external_account_id"], name="youtube_acc_externa_3f88c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="youtubeaccountconnection",
            index=models.Index(fields=["status"], name="youtube_acc_status_df5d37_idx"),
        ),
        migrations.AddConstraint(
            model_name="youtubeaccountconnection",
            constraint=models.UniqueConstraint(
                fields=("workspace", "external_account_id"), name="uniq_youtube_conn_per_workspace"
            ),
        ),
        migrations.AddIndex(
            model_name="youtubevideopost",
            index=models.Index(
                fields=["connection", "status"], name="youtube_vid_connect_de50ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="youtubevideopost",
            index=models.Index(
                fields=["status", "created_at"], name="youtube_vid_status_8cc1a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="youtubevideopost",
            index=models.Index(fields=["youtube_video_id"], name="youtube_vid_youtube_69462b_idx"),
        ),
    ]
