# Generated by Django 5.0.1 on 2026-05-07 09:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeSpamFilterConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "활성"), ("inactive", "비활성")],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("spam_keywords", models.JSONField(blank=True, default=list)),
                ("block_urls", models.BooleanField(default=True)),
                ("block_shortened_urls", models.BooleanField(default=True)),
                ("min_length", models.IntegerField(default=2)),
                ("max_emoji_ratio", models.FloatField(default=0.7)),
                ("max_mentions", models.IntegerField(default=3)),
                ("score_threshold", models.FloatField(default=1.0)),
                (
                    "default_action",
                    models.CharField(
                        choices=[("review", "heldForReview"), ("reject", "rejected")],
                        default="review",
                        help_text="review = comments.setModerationStatus(heldForReview); reject = comments.setModerationStatus(rejected). 각각 50 quota units.",
                        max_length=10,
                    ),
                ),
                (
                    "ban_authors_on_reject",
                    models.BooleanField(
                        default=False,
                        help_text="rejected 처리 시 banAuthor=true 추가. 향후 댓글도 자동 차단.",
                    ),
                ),
                ("total_spam_detected", models.IntegerField(default=0)),
                ("total_moderated", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spam_filter",
                        to="youtube.youtubeaccountconnection",
                    ),
                ),
            ],
            options={
                "db_table": "youtube_spam_filter_configs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="YouTubeCommentLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "external_video_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                ("external_thread_id", models.CharField(blank=True, default="", max_length=255)),
                ("external_comment_id", models.CharField(max_length=255)),
                ("commenter_channel_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "commenter_display_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("text", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("clean", "정상"),
                            ("detected", "스팸 감지"),
                            ("review", "heldForReview 처리"),
                            ("rejected", "rejected 처리"),
                            ("failed", "처리 실패"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True, default="")),
                ("api_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_logs",
                        to="youtube.youtubeaccountconnection",
                    ),
                ),
            ],
            options={
                "db_table": "youtube_comment_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["connection", "status"], name="youtube_com_connect_5330f7_idx"
                    ),
                    models.Index(
                        fields=["external_video_id"], name="youtube_com_externa_440e68_idx"
                    ),
                    models.Index(
                        fields=["external_comment_id"], name="youtube_com_externa_7e0b44_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="youtube_com_status_c1d22b_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="youtubecommentlog",
            constraint=models.UniqueConstraint(
                fields=("connection", "external_comment_id"),
                name="uniq_youtube_comment_per_connection",
            ),
        ),
        migrations.AddConstraint(
            model_name="youtubespamfilterconfig",
            constraint=models.UniqueConstraint(
                fields=("connection",), name="uniq_youtube_spam_filter_per_connection"
            ),
        ),
    ]
