# Generated by Django 5.0.1 on 2026-09-10 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspace", "0002_workspace_plan_workspace_workspaces_plan_c35e25_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeAlertDismissal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="apps.home.alerts 의 머신 키 (예: recent_post_no_campaign)",
                        max_length=64,
                        verbose_name="알림 코드",
                    ),
                ),
                (
                    "target_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="게시물 id · 페이지 id · 리포트 id 등. 대상이 없으면 빈 문자열.",
                        max_length=255,
                        verbose_name="대상 식별자",
                    ),
                ),
                ("dismissed_at", models.DateTimeField(auto_now_add=True, verbose_name="닫은 시각")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_alert_dismissals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_alert_dismissals",
                        to="workspace.workspace",
                        verbose_name="워크스페이스",
                    ),
                ),
            ],
            options={
                "verbose_name": "홈 알림 닫음",
                "verbose_name_plural": "홈 알림 닫음 목록",
                "db_table": "home_alert_dismissals",
                "ordering": ["-dismissed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "workspace"], name="home_alert__user_id_19abfb_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="homealertdismissal",
            constraint=models.UniqueConstraint(
                fields=("user", "workspace", "code", "target_key"), name="uq_home_alert_dismissal"
            ),
        ),
    ]
