# Generated by Django 5.0.1 on 2026-06-02 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user.update", "회원 정보 수정"),
                            ("user.password_reset", "회원 비밀번호 재설정 발송"),
                            ("workspace.update", "워크스페이스 수정"),
                            ("membership.update", "멤버 역할 변경"),
                            ("membership.delete", "멤버 제거"),
                            ("page.update", "페이지 차단/공개 변경"),
                            ("campaign.pause", "캠페인 일시중지"),
                            ("campaign.resume", "캠페인 재개"),
                            ("dmlog.retry", "DM 재시도"),
                            ("dmlog.reverify", "DM 재검증"),
                        ],
                        max_length=64,
                        verbose_name="액션",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(blank=True, max_length=32, verbose_name="대상 종류"),
                ),
                ("target_id", models.CharField(blank=True, max_length=64, verbose_name="대상 ID")),
                (
                    "target_repr",
                    models.CharField(blank=True, max_length=255, verbose_name="대상 표시명"),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="변경 내역(before/after)"
                    ),
                ),
                (
                    "request_id",
                    models.CharField(blank=True, max_length=64, verbose_name="X-Request-ID"),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="요청 IP")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="생성 시각"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수행 관리자",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Action Log",
                "verbose_name_plural": "Admin Action Logs",
                "db_table": "admin_action_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["actor"], name="admin_actio_actor_i_d938d8_idx"),
                    models.Index(fields=["action"], name="admin_actio_action_7568ff_idx"),
                    models.Index(
                        fields=["target_type", "target_id"], name="admin_actio_target__28c949_idx"
                    ),
                ],
            },
        ),
    ]
