# Generated by Django 5.0.1 on 2026-06-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminactionlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("user.update", "회원 정보 수정"),
                    ("user.password_reset", "회원 비밀번호 재설정 발송"),
                    ("user.subscription_update", "회원 구독(요금제) 변경"),
                    ("workspace.update", "워크스페이스 수정"),
                    ("membership.update", "멤버 역할 변경"),
                    ("membership.delete", "멤버 제거"),
                    ("page.update", "페이지 차단/공개 변경"),
                    ("campaign.pause", "캠페인 일시중지"),
                    ("campaign.resume", "캠페인 재개"),
                    ("dmlog.retry", "DM 재시도"),
                    ("dmlog.reverify", "DM 재검증"),
                ],
                max_length=64,
                verbose_name="액션",
            ),
        ),
    ]
