# Generated by Django 5.0.1 on 2026-07-26 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0003_alter_adminactionlog_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminactionlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("user.update", "회원 정보 수정"),
                    ("user.password_reset", "회원 비밀번호 재설정 발송"),
                    ("user.subscription_update", "회원 구독(요금제) 변경"),
                    ("workspace.update", "워크스페이스 수정"),
                    ("membership.update", "멤버 역할 변경"),
                    ("membership.delete", "멤버 제거"),
                    ("page.update", "페이지 차단/공개 변경"),
                    ("campaign.pause", "캠페인 일시중지"),
                    ("campaign.resume", "캠페인 재개"),
                    ("dmlog.retry", "DM 재시도"),
                    ("dmlog.reverify", "DM 재검증"),
                    ("referral.create", "레퍼럴 코드 생성"),
                    ("referral.update", "레퍼럴 코드 수정"),
                    ("referral.delete", "레퍼럴 코드 삭제"),
                    ("channel_link.create", "채널 링크 생성"),
                    ("channel_link.update", "채널 링크 수정"),
                    ("channel_link.delete", "채널 링크 삭제"),
                ],
                max_length=64,
                verbose_name="액션",
            ),
        ),
        migrations.CreateModel(
            name="MarketingChannelLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="링크 이름")),
                ("base_url", models.URLField(max_length=500, verbose_name="기본 URL")),
                ("utm_source", models.CharField(blank=True, default="", max_length=100)),
                ("utm_medium", models.CharField(blank=True, default="", max_length=100)),
                ("utm_campaign", models.CharField(blank=True, default="", max_length=100)),
                ("utm_content", models.CharField(blank=True, default="", max_length=100)),
                (
                    "url",
                    models.URLField(
                        help_text="base_url + utm 파라미터 조합 (서버 계산, 기존 동일 utm 키는 교체)",
                        max_length=1000,
                        verbose_name="완성 URL",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        help_text="derive_channel(utm_source, utm_medium) 결과 — 대시보드 채널 키와 동일 어휘",
                        max_length=32,
                        verbose_name="파생 채널 키",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 시각")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정 시각")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketing_channel_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성 관리자",
                    ),
                ),
            ],
            options={
                "verbose_name": "마케팅 채널 링크",
                "verbose_name_plural": "마케팅 채널 링크 목록",
                "db_table": "marketing_channel_links",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["channel"], name="marketing_c_channel_11c300_idx")
                ],
            },
        ),
    ]
