# Generated by Django 5.0.1 on 2026-07-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0004_alter_adminactionlog_action_marketingchannellink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminactionlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("user.update", "회원 정보 수정"),
                    ("user.password_reset", "회원 비밀번호 재설정 발송"),
                    ("user.subscription_update", "회원 구독(요금제) 변경"),
                    ("workspace.update", "워크스페이스 수정"),
                    ("membership.update", "멤버 역할 변경"),
                    ("membership.delete", "멤버 제거"),
                    ("page.update", "페이지 차단/공개 변경"),
                    ("campaign.pause", "캠페인 일시중지"),
                    ("campaign.resume", "캠페인 재개"),
                    ("dmlog.retry", "DM 재시도"),
                    ("dmlog.reverify", "DM 재검증"),
                    ("referral.create", "레퍼럴 코드 생성"),
                    ("referral.update", "레퍼럴 코드 수정"),
                    ("referral.delete", "레퍼럴 코드 삭제"),
                    ("channel_link.create", "채널 링크 생성"),
                    ("channel_link.update", "채널 링크 수정"),
                    ("channel_link.delete", "채널 링크 삭제"),
                    ("admin.access_denied", "어드민 접근 차단(권한 없음)"),
                ],
                max_length=64,
                verbose_name="액션",
            ),
        ),
    ]
