# Generated by Django 5.0.1 on 2026-07-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0005_alter_adminactionlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingchannellink",
            name="excluded_from_stats",
            field=models.BooleanField(
                default=False,
                help_text="채널별 성과·추이·퍼널에서 이 링크의 행을 빼고, 이 링크로 들어온 인원은 '기타' 행으로 흡수한다(인원을 총합에서 없애지는 않는다 — MKT-12). 테스트/오생성/종료된 캠페인 링크가 표에 쌓이는 것을 정리하는 용도.",
                verbose_name="집계 제외",
            ),
        ),
        migrations.AlterField(
            model_name="marketingchannellink",
            name="name",
            field=models.CharField(max_length=255, verbose_name="링크 이름"),
        ),
    ]
