# Generated by Django 5.0.1 on 2026-08-16 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0007_channel_link_utm_200_and_nfc_backfill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminactionlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("user.update", "회원 정보 수정"),
                    ("user.password_reset", "회원 비밀번호 재설정 발송"),
                    ("user.subscription_update", "회원 구독(요금제) 변경"),
                    ("workspace.update", "워크스페이스 수정"),
                    ("membership.update", "멤버 역할 변경"),
                    ("membership.delete", "멤버 제거"),
                    ("page.update", "페이지 차단/공개 변경"),
                    ("campaign.pause", "캠페인 일시중지"),
                    ("campaign.resume", "캠페인 재개"),
                    ("dmlog.retry", "DM 재시도"),
                    ("dmlog.reverify", "DM 재검증"),
                    ("referral.create", "레퍼럴 코드 생성"),
                    ("referral.update", "레퍼럴 코드 수정"),
                    ("referral.delete", "레퍼럴 코드 삭제"),
                    ("channel_link.create", "채널 링크 생성"),
                    ("channel_link.update", "채널 링크 수정"),
                    ("channel_link.delete", "채널 링크 삭제"),
                    ("admin.access_denied", "어드민 접근 차단(권한 없음)"),
                    ("admin.login", "어드민 로그인"),
                    ("admin.mfa_enrolled", "2단계 인증 등록"),
                    ("admin.mfa_reset", "2단계 인증 초기화"),
                    ("admin.backup_codes_regenerated", "백업코드 재발급"),
                    ("admin.device_trusted", "기기 신뢰 등록"),
                    ("admin.device_revoked", "기기 신뢰 해제"),
                ],
                max_length=64,
                verbose_name="액션",
            ),
        ),
        migrations.CreateModel(
            name="AdminDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("device_id", models.CharField(max_length=64, verbose_name="클라이언트 기기 ID")),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="기기 표시명"
                    ),
                ),
                (
                    "trusted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="신뢰 등록 시각(null=비신뢰)"
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="마지막 접속 시각"),
                ),
                (
                    "last_seen_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="마지막 접속 IP"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="해제 시각"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="최초 로그인 시각"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="관리자",
                    ),
                ),
            ],
            options={
                "verbose_name": "어드민 기기",
                "verbose_name_plural": "어드민 기기 목록",
                "db_table": "admin_devices",
                "ordering": ["-last_seen_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminMFADevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "_encrypted_secret",
                    models.TextField(blank=True, default="", verbose_name="암호화된 TOTP 시드"),
                ),
                (
                    "_encrypted_pending_secret",
                    models.TextField(
                        blank=True, default="", verbose_name="등록 중인 시드(확인 전)"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="등록 확인 시각(첫 코드 검증 성공)"
                    ),
                ),
                (
                    "last_step",
                    models.BigIntegerField(
                        default=0,
                        help_text="재사용 방지 — 이 값 이하 스텝은 거부",
                        verbose_name="마지막 성공 스텝",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 시각")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_mfa_device",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="관리자",
                    ),
                ),
            ],
            options={
                "verbose_name": "어드민 2단계 인증",
                "verbose_name_plural": "어드민 2단계 인증 목록",
                "db_table": "admin_mfa_devices",
            },
        ),
        migrations.CreateModel(
            name="AdminBackupCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(db_index=True, max_length=64, verbose_name="sha256(코드)"),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True, verbose_name="사용 시각")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="발급 시각")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_backup_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="관리자",
                    ),
                ),
            ],
            options={
                "verbose_name": "어드민 백업코드",
                "verbose_name_plural": "어드민 백업코드 목록",
                "db_table": "admin_backup_codes",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["user", "used_at"], name="admin_backu_user_id_caf913_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="admindevice",
            constraint=models.UniqueConstraint(
                fields=("user", "device_id"), name="uniq_admin_device_per_user"
            ),
        ),
    ]
