# Generated by Django 5.0.1 on 2026-08-16 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0008_alter_adminactionlog_action_admindevice_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="화면 설정(자유 JSON)"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정 시각")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="관리자",
                    ),
                ),
            ],
            options={
                "verbose_name": "어드민 화면 설정",
                "verbose_name_plural": "어드민 화면 설정 목록",
                "db_table": "admin_preferences",
            },
        ),
    ]
