# Generated by Django 5.0.1 on 2026-02-04 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="plan",
            field=models.CharField(
                choices=[("starter", "Starter"), ("pro", "Pro"), ("enterprise", "Enterprise")],
                default="starter",
                max_length=20,
                verbose_name="Subscription Plan",
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(fields=["plan"], name="workspaces_plan_c35e25_idx"),
        ),
    ]
