# Generated by Django 5.0.1 on 2026-10-08 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("phone_verify", "휴대폰 본인확인"), ("notice", "정보성 안내")],
                        db_index=True,
                        default="phone_verify",
                        max_length=32,
                    ),
                ),
                (
                    "to_phone",
                    models.CharField(db_index=True, max_length=20, verbose_name="수신번호(숫자만)"),
                ),
                (
                    "sender",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="발신번호"
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True, default="", verbose_name="본문(인증번호 마스킹됨)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("mocked", "Mocked"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("provider", models.CharField(default="aligo", max_length=16)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "result_code",
                    models.IntegerField(blank=True, null=True, verbose_name="알리고 result_code"),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("request_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS 발송 로그",
                "verbose_name_plural": "SMS 발송 로그 목록",
                "db_table": "sms_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["to_phone", "created_at"], name="sms_logs_to_phon_5c0286_idx"
                    ),
                    models.Index(
                        fields=["purpose", "status", "created_at"],
                        name="sms_logs_purpose_613d4d_idx",
                    ),
                ],
            },
        ),
    ]
