# Generated by Django 5.0.1 on 2026-05-07 08:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspace", "0002_workspace_plan_workspace_workspaces_plan_c35e25_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="TikTokAccountConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "external_account_id",
                    models.CharField(db_index=True, max_length=255, verbose_name="TikTok open_id"),
                ),
                (
                    "union_id",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="TikTok union_id"
                    ),
                ),
                (
                    "username",
                    models.CharField(blank=True, max_length=255, verbose_name="Display name"),
                ),
                ("avatar_url", models.URLField(blank=True, default="", verbose_name="Avatar URL")),
                (
                    "_encrypted_access_token",
                    models.TextField(verbose_name="Encrypted Access Token"),
                ),
                (
                    "_encrypted_refresh_token",
                    models.TextField(
                        blank=True, default="", verbose_name="Encrypted Refresh Token"
                    ),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("refresh_token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("scopes", models.JSONField(default=list, verbose_name="Granted scopes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "is_audited",
                    models.BooleanField(
                        default=False,
                        help_text="False = unaudited TikTok client. Every publish call is forced to privacy_level=SELF_ONLY regardless of caller intent.",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiktok_connections",
                        to="workspace.workspace",
                        verbose_name="Workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "TikTok Account Connection",
                "verbose_name_plural": "TikTok Account Connections",
                "db_table": "tiktok_account_connections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TikTokOAuthState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("state", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "code_verifier",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="PKCE code_verifier (S256)",
                        max_length=128,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiktok_oauth_states",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "TikTok OAuth State",
                "verbose_name_plural": "TikTok OAuth States",
                "db_table": "tiktok_oauth_states",
            },
        ),
        migrations.CreateModel(
            name="TikTokVideoPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        blank=True, default="", verbose_name="캡션 (마크업/해시태그 포함)"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("FILE_UPLOAD", "FILE_UPLOAD"),
                            ("PULL_FROM_URL", "PULL_FROM_URL"),
                        ],
                        default="PULL_FROM_URL",
                        max_length=20,
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="PULL_FROM_URL 방식의 원본 영상 URL. TikTok이 직접 fetch.",
                    ),
                ),
                (
                    "video_file_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="FILE_UPLOAD 방식의 서버 로컬/스토리지 경로",
                        max_length=500,
                    ),
                ),
                ("video_size_bytes", models.BigIntegerField(default=0)),
                (
                    "requested_privacy",
                    models.CharField(
                        choices=[
                            ("PUBLIC_TO_EVERYONE", "공개"),
                            ("MUTUAL_FOLLOW_FRIENDS", "친구만"),
                            ("FOLLOWER_OF_CREATOR", "팔로워만"),
                            ("SELF_ONLY", "비공개"),
                        ],
                        default="SELF_ONLY",
                        max_length=30,
                    ),
                ),
                (
                    "effective_privacy",
                    models.CharField(
                        choices=[
                            ("PUBLIC_TO_EVERYONE", "공개"),
                            ("MUTUAL_FOLLOW_FRIENDS", "친구만"),
                            ("FOLLOWER_OF_CREATOR", "팔로워만"),
                            ("SELF_ONLY", "비공개"),
                        ],
                        default="SELF_ONLY",
                        help_text="실제 TikTok에 전달된 privacy. 미감사 시 SELF_ONLY로 강제됨.",
                        max_length=30,
                    ),
                ),
                ("disable_duet", models.BooleanField(default=False)),
                ("disable_comment", models.BooleanField(default=False)),
                ("disable_stitch", models.BooleanField(default=False)),
                ("auto_add_music", models.BooleanField(default=False)),
                (
                    "publish_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                ("upload_url", models.URLField(blank=True, default="")),
                ("tiktok_video_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "큐 대기"),
                            ("initiating", "TikTok init 호출 중"),
                            ("uploading", "파일 업로드 중"),
                            ("processing", "TikTok 처리 중"),
                            ("published", "발행 완료"),
                            ("failed", "발행 실패"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("fail_reason", models.TextField(blank=True, default="")),
                ("api_response", models.JSONField(blank=True, default=dict)),
                ("retry_count", models.IntegerField(default=0)),
                ("next_check_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("initiated_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_posts",
                        to="tiktok.tiktokaccountconnection",
                        verbose_name="TikTok Connection",
                    ),
                ),
            ],
            options={
                "verbose_name": "TikTok Video Post",
                "verbose_name_plural": "TikTok Video Posts",
                "db_table": "tiktok_video_posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tiktokaccountconnection",
            index=models.Index(
                fields=["workspace", "status"], name="tiktok_acco_workspa_a9f053_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tiktokaccountconnection",
            index=models.Index(
                fields=["external_account_id"], name="tiktok_acco_externa_7d5822_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tiktokaccountconnection",
            index=models.Index(fields=["status"], name="tiktok_acco_status_ce7e47_idx"),
        ),
        migrations.AddConstraint(
            model_name="tiktokaccountconnection",
            constraint=models.UniqueConstraint(
                fields=("workspace", "external_account_id"), name="uniq_tiktok_conn_per_workspace"
            ),
        ),
        migrations.AddIndex(
            model_name="tiktokvideopost",
            index=models.Index(
                fields=["connection", "status"], name="tiktok_vide_connect_71b5ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tiktokvideopost",
            index=models.Index(
                fields=["status", "created_at"], name="tiktok_vide_status_6e5a38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tiktokvideopost",
            index=models.Index(fields=["publish_id"], name="tiktok_vide_publish_88f558_idx"),
        ),
    ]
