# Generated by Django 5.0.1 on 2026-05-07 09:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiktok", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TikTokSpamFilterConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "활성"), ("inactive", "비활성")],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("spam_keywords", models.JSONField(blank=True, default=list)),
                ("block_urls", models.BooleanField(default=True)),
                ("block_shortened_urls", models.BooleanField(default=True)),
                ("min_length", models.IntegerField(default=2)),
                ("max_emoji_ratio", models.FloatField(default=0.7)),
                ("max_mentions", models.IntegerField(default=3)),
                ("score_threshold", models.FloatField(default=1.0)),
                (
                    "default_action",
                    models.CharField(
                        choices=[("review", "검토 큐로"), ("hide", "숨김")],
                        default="review",
                        max_length=10,
                    ),
                ),
                ("total_spam_detected", models.IntegerField(default=0)),
                ("total_hidden", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spam_filter",
                        to="tiktok.tiktokaccountconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "TikTok Spam Filter Config",
                "verbose_name_plural": "TikTok Spam Filter Configs",
                "db_table": "tiktok_spam_filter_configs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TikTokCommentLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("external_video_id", models.CharField(db_index=True, max_length=255)),
                ("external_comment_id", models.CharField(max_length=255)),
                ("commenter_external_id", models.CharField(blank=True, default="", max_length=255)),
                ("commenter_username", models.CharField(blank=True, default="", max_length=255)),
                ("text", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("clean", "정상"),
                            ("detected", "스팸 감지"),
                            ("hidden", "숨김 완료"),
                            ("review", "검토 대기"),
                            ("failed", "처리 실패"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True, default="")),
                ("api_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_logs",
                        to="tiktok.tiktokaccountconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "TikTok Comment Log",
                "verbose_name_plural": "TikTok Comment Logs",
                "db_table": "tiktok_comment_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["connection", "status"], name="tiktok_comm_connect_94734c_idx"
                    ),
                    models.Index(
                        fields=["external_video_id"], name="tiktok_comm_externa_1c6814_idx"
                    ),
                    models.Index(
                        fields=["external_comment_id"], name="tiktok_comm_externa_ac2dd7_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="tiktok_comm_status_9c5367_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tiktokcommentlog",
            constraint=models.UniqueConstraint(
                fields=("connection", "external_comment_id"),
                name="uniq_tiktok_comment_per_connection",
            ),
        ),
        migrations.AddConstraint(
            model_name="tiktokspamfilterconfig",
            constraint=models.UniqueConstraint(
                fields=("connection",), name="uniq_tiktok_spam_filter_per_connection"
            ),
        ),
    ]
