# Generated by Django 5.0.1 on 2026-05-11 06:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiktok", "0002_tiktokspamfilterconfig_tiktokcommentlog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TikTokBlockedWord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("word", models.CharField(max_length=255)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="TikTok 측 blockedword id (확인된 경우만)",
                        max_length=255,
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(
                        default=False,
                        help_text="False = 로컬에만 있음 / True = TikTok 측에도 반영 완료",
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "TikTok Blocked Word",
                "verbose_name_plural": "TikTok Blocked Words",
                "db_table": "tiktok_blocked_words",
                "ordering": ["word"],
            },
        ),
        migrations.RemoveField(
            model_name="tiktokvideopost",
            name="connection",
        ),
        migrations.RemoveIndex(
            model_name="tiktokcommentlog",
            name="tiktok_comm_externa_1c6814_idx",
        ),
        migrations.RemoveField(
            model_name="tiktokaccountconnection",
            name="avatar_url",
        ),
        migrations.RemoveField(
            model_name="tiktokaccountconnection",
            name="is_audited",
        ),
        migrations.RemoveField(
            model_name="tiktokaccountconnection",
            name="refresh_token_expires_at",
        ),
        migrations.RemoveField(
            model_name="tiktokaccountconnection",
            name="union_id",
        ),
        migrations.RemoveField(
            model_name="tiktokaccountconnection",
            name="username",
        ),
        migrations.RemoveField(
            model_name="tiktokcommentlog",
            name="external_video_id",
        ),
        migrations.RemoveField(
            model_name="tiktokoauthstate",
            name="code_verifier",
        ),
        migrations.AddField(
            model_name="tiktokaccountconnection",
            name="advertiser_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="광고 계정명"
            ),
        ),
        migrations.AddField(
            model_name="tiktokaccountconnection",
            name="bc_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Business Center ID"
            ),
        ),
        migrations.AddField(
            model_name="tiktokcommentlog",
            name="ad_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="tiktokcommentlog",
            name="advertiser_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="tiktokcommentlog",
            name="creative_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="tiktokcommentlog",
            name="parent_comment_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="tiktokspamfilterconfig",
            name="total_deleted",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tiktokaccountconnection",
            name="external_account_id",
            field=models.CharField(db_index=True, max_length=255, verbose_name="advertiser_id"),
        ),
        migrations.AlterField(
            model_name="tiktokaccountconnection",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("revoked", "Revoked"),
                    ("error", "Error"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tiktokcommentlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "대기"),
                    ("clean", "정상"),
                    ("detected", "스팸 감지"),
                    ("hidden", "숨김 완료"),
                    ("deleted", "삭제 완료"),
                    ("review", "검토 대기"),
                    ("failed", "처리 실패"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tiktokspamfilterconfig",
            name="default_action",
            field=models.CharField(
                choices=[("review", "검토 큐로"), ("hide", "숨김"), ("delete", "삭제")],
                default="review",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="tiktokcommentlog",
            index=models.Index(fields=["ad_id"], name="tiktok_comm_ad_id_7e311f_idx"),
        ),
        migrations.AddField(
            model_name="tiktokblockedword",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_words",
                to="tiktok.tiktokaccountconnection",
            ),
        ),
        migrations.DeleteModel(
            name="TikTokVideoPost",
        ),
        migrations.AddIndex(
            model_name="tiktokblockedword",
            index=models.Index(
                fields=["connection", "word"], name="tiktok_bloc_connect_c5cb09_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tiktokblockedword",
            constraint=models.UniqueConstraint(
                fields=("connection", "word"), name="uniq_tiktok_blockedword_per_connection"
            ),
        ),
    ]
