# Generated by Django 5.0.1 on 2026-03-03 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="공개 URL 식별자. 사용자명 변경 시 자동 갱신되지 않습니다.",
                        max_length=120,
                        unique=True,
                        verbose_name="공개 URL slug",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="페이지 제목"
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="공개 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="소유자",
                    ),
                ),
            ],
            options={
                "verbose_name": "페이지",
                "verbose_name_plural": "페이지 목록",
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("profile", "프로필"),
                            ("contact", "연락처"),
                            ("single_link", "단일 링크"),
                        ],
                        max_length=50,
                        verbose_name="블록 타입",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="표시 순서")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="노출 여부")),
                ("data", models.JSONField(default=dict, verbose_name="블록 데이터")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="pages.page",
                        verbose_name="페이지",
                    ),
                ),
            ],
            options={
                "verbose_name": "블록",
                "verbose_name_plural": "블록 목록",
                "ordering": ["order"],
                "indexes": [
                    models.Index(fields=["page", "type"], name="pages_block_page_id_c0d87b_idx")
                ],
                "unique_together": {("page", "order")},
            },
        ),
    ]
