# Generated by Django 5.0.1 on 2026-03-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="hide_at",
            field=models.DateTimeField(
                blank=True,
                help_text="이 시각 이후부터 공개 페이지에서 숨겨집니다. (schedule_enabled=True일 때만 적용)",
                null=True,
                verbose_name="숨김 시작 일시",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="이 시각 이후부터 공개 페이지에 노출됩니다. (schedule_enabled=True일 때만 적용)",
                null=True,
                verbose_name="공개 시작 일시",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="schedule_enabled",
            field=models.BooleanField(
                default=False,
                help_text="True이면 publish_at/hide_at 기준으로 공개 여부를 자동 제어합니다.",
                verbose_name="예약 설정 활성화",
            ),
        ),
    ]
