# Generated by Django 5.0.1 on 2026-03-09 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_block_hide_at_block_publish_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "clicked_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="클릭 일시"
                    ),
                ),
                (
                    "referer",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="유입 채널 URL"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", max_length=2, verbose_name="유입 국가"
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="IP 해시"),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="pages.block",
                        verbose_name="블록",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="집계 쿼리 최적화를 위해 비정규화 저장.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_clicks",
                        to="pages.page",
                        verbose_name="페이지",
                    ),
                ),
            ],
            options={
                "verbose_name": "블록 클릭",
                "verbose_name_plural": "블록 클릭 목록",
                "indexes": [
                    models.Index(
                        fields=["page", "clicked_at"], name="pages_block_page_id_dacc4b_idx"
                    ),
                    models.Index(
                        fields=["block", "clicked_at"], name="pages_block_block_i_d87f22_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="조회 일시"
                    ),
                ),
                (
                    "referer",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="HTTP Referer 헤더 원문. 집계 시 도메인으로 파싱됩니다.",
                        max_length=500,
                        verbose_name="유입 채널 URL",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ISO 3166-1 alpha-2 코드 (예: KR, US). Cloudflare CF-IPCountry 헤더 기반.",
                        max_length=2,
                        verbose_name="유입 국가",
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256(IP). 개인정보 보호를 위해 원본 IP는 저장하지 않습니다.",
                        max_length=64,
                        verbose_name="IP 해시",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="pages.page",
                        verbose_name="페이지",
                    ),
                ),
            ],
            options={
                "verbose_name": "페이지 조회",
                "verbose_name_plural": "페이지 조회 목록",
                "indexes": [
                    models.Index(
                        fields=["page", "viewed_at"], name="pages_pagev_page_id_63cf90_idx"
                    ),
                    models.Index(fields=["page", "country"], name="pages_pagev_page_id_c34a76_idx"),
                ],
            },
        ),
    ]
