# Generated by Django 5.0.1 on 2026-03-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_blockclick_pageview"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="프론트엔드가 자유롭게 저장하는 페이지 설정 (테마, 배경색, 폰트 등). 서버는 구조를 강제하지 않습니다.",
                verbose_name="페이지 설정 데이터",
            ),
        ),
    ]
