# Generated by Django 5.0.1 on 2026-03-10 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_page_add_data_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="보낸 사람")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "일반 문의"),
                            ("business", "비즈니스 협업"),
                            ("support", "고객 지원"),
                            ("other", "기타"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="분류",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="이메일"
                    ),
                ),
                ("phone", models.CharField(max_length=30, verbose_name="휴대폰번호")),
                ("subject", models.CharField(max_length=255, verbose_name="문의 제목")),
                ("content", models.TextField(blank=True, default="", verbose_name="문의 내용")),
                (
                    "agreed_to_terms",
                    models.BooleanField(
                        default=False, verbose_name="이용약관 및 개인정보 처리방침 동의"
                    ),
                ),
                (
                    "memo",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="작성 내용은 확인용으로, 문의 고객에게 전달되지 않습니다.",
                        verbose_name="관리자 메모",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="문의 일시"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="pages.page",
                        verbose_name="페이지",
                    ),
                ),
            ],
            options={
                "verbose_name": "문의",
                "verbose_name_plural": "문의 목록",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["page", "created_at"], name="pages_conta_page_id_2e2c7f_idx"
                    ),
                    models.Index(
                        fields=["page", "category"], name="pages_conta_page_id_64b1ff_idx"
                    ),
                ],
            },
        ),
    ]
