# Generated by Django 5.0.1 on 2026-03-16 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_add_pagemedia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pagemedia",
            new_name="pages_pagem_page_id_6c7cb1_idx",
            old_name="pages_media_page_created_idx",
        ),
        migrations.RenameIndex(
            model_name="pagesubscription",
            new_name="pages_pages_page_id_eb541a_idx",
            old_name="pages_pages_page_id_creat_idx",
        ),
        migrations.RenameIndex(
            model_name="pagesubscription",
            new_name="pages_pages_page_id_0f1d06_idx",
            old_name="pages_pages_page_id_categ_idx",
        ),
        migrations.AlterField(
            model_name="page",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="소유자",
            ),
        ),
    ]
