# Generated by Django 5.0.1 on 2026-03-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_page_user_foreignkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockclick",
            name="link_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="social 블록의 플랫폼 키(instagram, youtube 등), group_link의 개별 링크 ID. 빈 문자열이면 블록 단위 클릭.",
                max_length=200,
                verbose_name="서브링크 ID",
            ),
        ),
        migrations.AddIndex(
            model_name="blockclick",
            index=models.Index(
                fields=["block", "link_id", "clicked_at"], name="pages_block_block_i_4aabfb_idx"
            ),
        ),
    ]
