# Generated by Django 5.0.1 on 2026-03-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_blockclick_link_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="custom_css",
            field=models.TextField(
                blank=True,
                default="",
                help_text="사용자가 자유롭게 작성하는 CSS. 공개 페이지 렌더링 시 <style> 태그로 주입됩니다.",
                verbose_name="커스텀 CSS",
            ),
        ),
    ]
