# Generated by Django 5.0.1 on 2026-03-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_page_custom_css"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="custom_css",
            field=models.TextField(
                blank=True,
                default="",
                help_text="블록에 적용할 커스텀 CSS. 공개 페이지 렌더링 시 해당 블록 영역에 주입.",
                verbose_name="커스텀 CSS",
            ),
        ),
    ]
