# Generated by Django 5.0.1 on 2026-04-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_block_custom_css"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagemedia",
            name="crop_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="이미지 편집 파라미터. {x, y, width, height, aspect_ratio, locked, rotation, original_width, original_height}. 빈 dict이면 (기존 이미지) 프론트에서 전체 영역(최대 크롭)으로 간주합니다.",
                verbose_name="크롭 파라미터",
            ),
        ),
        migrations.AddField(
            model_name="pagemedia",
            name="original_file",
            field=models.FileField(
                blank=True,
                help_text="크롭/편집하기 전의 원본 이미지. 재편집 시 이 파일로 편집기를 복원합니다.",
                null=True,
                upload_to="pages/originals/%Y/%m/",
                verbose_name="편집 전 원본 파일",
            ),
        ),
        migrations.AlterField(
            model_name="pagemedia",
            name="file",
            field=models.FileField(
                help_text="편집(크롭) 완료된 최종 이미지. 블록 렌더링에 사용.",
                upload_to="pages/%Y/%m/",
                verbose_name="완성(크롭) 파일",
            ),
        ),
    ]
