# Generated by Django 5.0.1 on 2026-06-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0019_seed_reference_categories"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pagesnapshot",
            new_name="pages_pages_page_id_1e184e_idx",
            old_name="pages_pages_page_id_b8f1c4_idx",
        ),
        migrations.AlterField(
            model_name="pagesnapshot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
