# Generated by Django 5.0.1 on 2026-06-08 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pages",
            "0020_rename_pages_pages_page_id_b8f1c4_idx_pages_pages_page_id_1e184e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="current_snapshot",
            field=models.ForeignKey(
                blank=True,
                help_text="라이브 페이지가 현재 일치하는 스냅샷. AI 편집/복원 직후 설정되고, 사용자가 직접 편집하면 NULL 로 초기화된다.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="pages.pagesnapshot",
                verbose_name="현재 활성 스냅샷",
            ),
        ),
    ]
