# Generated by Django 5.0.1 on 2026-06-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0021_page_current_snapshot"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pagesnapshot",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="pagesnapshot",
            name="reason",
            field=models.CharField(
                choices=[
                    ("ai_edit", "AI 편집 직전 원본"),
                    ("ai_result", "AI 작업물"),
                    ("restore", "복원 직전 상태"),
                    ("latest_ai_result", "AI 작업물"),
                ],
                help_text="어떤 작업 직전에 떠둔 스냅샷인지.",
                max_length=30,
                verbose_name="생성 사유",
            ),
        ),
    ]
