# Generated by Django 5.0.1 on 2026-07-11 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "visitor_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="클라이언트가 생성해 localStorage(tf_vid)에 영구 보관하는 UUID.",
                        verbose_name="방문자 ID",
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="utm_source"
                    ),
                ),
                (
                    "utm_medium",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="utm_medium"
                    ),
                ),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="utm_campaign"
                    ),
                ),
                (
                    "utm_content",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="utm_content"
                    ),
                ),
                (
                    "referrer",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="document.referrer 원문 (500자 절단). 채널 파생은 저장 시점에 수행.",
                        max_length=500,
                        verbose_name="리퍼러 URL",
                    ),
                ),
                (
                    "landing_path",
                    models.CharField(
                        blank=True, default="/", max_length=300, verbose_name="랜딩 경로"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        db_index=True,
                        default="direct",
                        help_text="channels.derive_channel() 로 저장 시점에 파생된 채널 키 (예: meta_ads).",
                        max_length=32,
                        verbose_name="유입 채널",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ISO 3166-1 alpha-2 (CF-IPCountry 헤더 우선).",
                        max_length=2,
                        verbose_name="유입 국가",
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256(IP). 개인정보 보호를 위해 원본 IP는 저장하지 않습니다.",
                        max_length=64,
                        verbose_name="IP 해시",
                    ),
                ),
                (
                    "ua_class",
                    models.CharField(
                        choices=[
                            ("desktop", "데스크톱"),
                            ("mobile", "모바일"),
                            ("tablet", "태블릿"),
                            ("bot", "봇"),
                            ("unknown", "알 수 없음"),
                        ],
                        default="unknown",
                        max_length=10,
                        verbose_name="UA 분류",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="방문 일시"
                    ),
                ),
            ],
            options={
                "verbose_name": "랜딩 방문",
                "verbose_name_plural": "랜딩 방문 목록",
                "db_table": "analytics_landing_visit",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["channel", "created_at"], name="analytics_l_channel_873e25_idx"
                    ),
                    models.Index(
                        fields=["visitor_id", "created_at"], name="analytics_l_visitor_628bbe_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SignupAttribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "visitor_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="LandingVisit 과 조인하는 키. 랜딩을 거치지 않은 가입은 NULL.",
                        null=True,
                        verbose_name="방문자 ID",
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="utm_source"
                    ),
                ),
                (
                    "utm_medium",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="utm_medium"
                    ),
                ),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="utm_campaign"
                    ),
                ),
                (
                    "utm_content",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="utm_content"
                    ),
                ),
                (
                    "referrer",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="리퍼러 URL"
                    ),
                ),
                (
                    "landing_path",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="랜딩 경로"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        db_index=True,
                        default="unknown",
                        help_text="channels.derive_channel() 파생 키. referral 은 조회 시점 오버레이(모델 docstring).",
                        max_length=32,
                        verbose_name="유입 채널",
                    ),
                ),
                (
                    "signup_kind",
                    models.CharField(
                        choices=[("email", "이메일 가입"), ("google", "Google 가입")],
                        max_length=10,
                        verbose_name="가입 경로",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="가입 일시"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signup_attribution",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="가입 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "가입 귀속",
                "verbose_name_plural": "가입 귀속 목록",
                "db_table": "analytics_signup_attribution",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["channel", "created_at"], name="analytics_s_channel_9d6705_idx"
                    )
                ],
            },
        ),
    ]
