# Generated by Django 5.0.1 on 2026-07-12 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("pricing_page_viewed", "가격표 조회"),
                            ("paywall_viewed", "유료 제한 모달 노출"),
                            ("paywall_cta_clicked", "업그레이드 버튼 클릭"),
                            ("checkout_started", "결제 시작"),
                            ("plan_selected", "플랜 선택"),
                            ("feature_limit_reached", "기능 한도 도달"),
                            ("premium_feature_attempted", "유료 기능 시도"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="이벤트",
                    ),
                ),
                (
                    "entry_source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="paywall / pricing_page / upgrade_button / direct 등 (프론트 정의 어휘).",
                        max_length=40,
                        verbose_name="진입 소스",
                    ),
                ),
                (
                    "trigger_feature",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="dm_limit / page_limit / badge_removal / spam_advanced / multi_ig / ai_page / analytics_export / pricing_direct 등 — 진입 경로 귀속의 핵심 축.",
                        max_length=40,
                        verbose_name="트리거 기능",
                    ),
                ),
                (
                    "source_page",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="발생 화면"
                    ),
                ),
                (
                    "current_plan",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="현재 플랜"
                    ),
                ),
                (
                    "required_plan",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="필요 플랜"
                    ),
                ),
                (
                    "selected_plan",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="선택 플랜"
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        blank=True,
                        help_text="한도 도달 시 현재 사용량.",
                        null=True,
                        verbose_name="사용량",
                    ),
                ),
                (
                    "limit_count",
                    models.IntegerField(
                        blank=True,
                        help_text="한도 도달 시 플랜 한도.",
                        null=True,
                        verbose_name="한도",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="발생 일시"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="로그인 사용자. 비로그인 가격표 조회 등은 NULL 가능.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "결제 진입 이벤트",
                "verbose_name_plural": "결제 진입 이벤트 목록",
                "db_table": "analytics_checkout_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"], name="analytics_c_user_id_531204_idx"
                    ),
                    models.Index(
                        fields=["trigger_feature", "created_at"],
                        name="analytics_c_trigger_5fdf0c_idx",
                    ),
                ],
            },
        ),
    ]
