# Generated by Django 5.0.1 on 2026-07-12 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_checkoutevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CancellationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("cancel_button_clicked", "취소 버튼 클릭"),
                            ("cancel_reason_submitted", "해지 사유 제출"),
                            ("subscription_cancel_scheduled", "구독 취소 예약"),
                            ("subscription_cancel_aborted", "취소 중단(유지 선택)"),
                            ("subscription_resumed", "취소 예약 철회"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="이벤트",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="price / low_usage / no_effect / hard_setup / missing_feature / ig_error / switched / paused / other 등 (프론트 정의 어휘).",
                        max_length=40,
                        verbose_name="해지 사유",
                    ),
                ),
                (
                    "reason_detail",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="사유 상세(자유입력)"
                    ),
                ),
                (
                    "from_plan",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="이전 플랜"
                    ),
                ),
                (
                    "to_plan",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="이후 플랜"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="발생 일시"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "구독 취소 이벤트",
                "verbose_name_plural": "구독 취소 이벤트 목록",
                "db_table": "analytics_cancellation_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"], name="analytics_c_user_id_e68104_idx"
                    ),
                    models.Index(
                        fields=["event", "created_at"], name="analytics_c_event_6b9e96_idx"
                    ),
                    models.Index(
                        fields=["reason", "created_at"], name="analytics_c_reason_dec9cb_idx"
                    ),
                ],
            },
        ),
    ]
