# Generated by Django 5.0.1 on 2026-07-22 00:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_cancellationevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cancellationevent",
            name="offer",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="offer_* 이벤트의 대상 오퍼 (예: downgrade_basic / pause / discount_50). 오퍼별 방어율 퍼널의 축.",
                max_length=40,
                verbose_name="리텐션 오퍼",
            ),
        ),
        migrations.AlterField(
            model_name="cancellationevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("cancel_button_clicked", "취소 버튼 클릭"),
                    ("cancel_reason_submitted", "해지 사유 제출"),
                    ("subscription_cancel_scheduled", "구독 취소 예약"),
                    ("subscription_cancel_aborted", "취소 중단(유지 선택)"),
                    ("subscription_resumed", "취소 예약 철회"),
                    ("offer_shown", "오퍼 단계 노출"),
                    ("offer_accepted", "오퍼 수락"),
                    ("offer_declined", "오퍼 거절(계속 해지)"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="이벤트",
            ),
        ),
        migrations.AddIndex(
            model_name="cancellationevent",
            index=models.Index(fields=["offer", "created_at"], name="analytics_c_offer_a6df0c_idx"),
        ),
    ]
