# Generated by Django 5.0.1 on 2026-08-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0005_utm_length_200_and_nfc_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="signupattribution",
            name="fbc",
            field=models.CharField(
                blank=True,
                default="",
                help_text="fbclid 로부터 픽셀이 만든 값 (fb.1.<ts>.<fbclid>).",
                max_length=300,
                verbose_name="_fbc 쿠키",
            ),
        ),
        migrations.AddField(
            model_name="signupattribution",
            name="fbclid",
            field=models.CharField(
                blank=True,
                default="",
                help_text="광고 클릭 시 URL 에 붙는 Meta 클릭 ID.",
                max_length=500,
                verbose_name="fbclid",
            ),
        ),
        migrations.AddField(
            model_name="signupattribution",
            name="fbp",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Meta 픽셀이 브라우저에 심는 식별자.",
                max_length=200,
                verbose_name="_fbp 쿠키",
            ),
        ),
    ]
