# Generated by Django 5.0.1 on 2026-09-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0006_signupattribution_fbc_signupattribution_fbclid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signupattribution",
            name="signup_kind",
            field=models.CharField(
                choices=[
                    ("email", "이메일 가입"),
                    ("google", "Google 가입"),
                    ("kakao", "카카오 가입"),
                ],
                max_length=10,
                verbose_name="가입 경로",
            ),
        ),
    ]
