# Generated by Django 5.0.1 on 2026-09-12 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_alter_signupattribution_signup_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FunnelEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event",
                    models.CharField(
                        db_index=True,
                        help_text="프론트 FunnelEventName 이 정본 (예: trial_popup_view, trial_started_from_popup)",
                        max_length=60,
                        verbose_name="이벤트 이름",
                    ),
                ),
                (
                    "visitor_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="랜딩 스니펫의 tf_vid. LandingVisit·SignupAttribution 과 조인하는 키.",
                        null=True,
                        verbose_name="방문자 ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="발생 화면 경로"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="이벤트별 자유 필드(surface, attempt, method, elapsed_sec …). 상한 4KB.",
                        verbose_name="이벤트 필드",
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("pc", "PC"),
                            ("unknown", "알 수 없음"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=10,
                        verbose_name="기기",
                    ),
                ),
                ("in_app", models.BooleanField(default=False, verbose_name="인앱 브라우저 여부")),
                (
                    "in_app_kind",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="instagram / kakaotalk / facebook / line / naver 등. 프론트 판별값.",
                        max_length=24,
                        verbose_name="인앱 브라우저 종류",
                    ),
                ),
                (
                    "ua_class",
                    models.CharField(
                        choices=[
                            ("desktop", "데스크톱"),
                            ("mobile", "모바일"),
                            ("tablet", "태블릿"),
                            ("bot", "봇"),
                            ("unknown", "알 수 없음"),
                        ],
                        default="unknown",
                        max_length=10,
                        verbose_name="UA 대분류(서버 파생)",
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="IP 해시(SHA-256)"
                    ),
                ),
                (
                    "client_ts",
                    models.DateTimeField(
                        blank=True,
                        help_text="프론트가 보낸 ts. 기기 시계가 틀릴 수 있어 집계는 created_at 을 쓴다.",
                        null=True,
                        verbose_name="클라이언트 시각",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="수신 시각"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="비로그인 이벤트도 받으므로 NULL 가능. 사용자 삭제 시 행은 남기고 NULL 로.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="funnel_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "퍼널 이벤트",
                "verbose_name_plural": "퍼널 이벤트 목록",
                "db_table": "analytics_funnel_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "created_at"], name="analytics_f_event_c57264_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="analytics_f_user_id_b10669_idx"
                    ),
                    models.Index(
                        fields=["device", "created_at"], name="analytics_f_device_280931_idx"
                    ),
                ],
            },
        ),
    ]
