# Generated by Django 5.0.1 on 2026-07-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_email_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="marketing_opt_in",
            field=models.BooleanField(default=False, verbose_name="마케팅 수신 동의"),
        ),
        migrations.AddField(
            model_name="user",
            name="marketing_opt_in_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="마케팅 수신 동의 시각"),
        ),
    ]
