# Generated by Django 5.0.1 on 2026-08-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_user_marketing_opt_in_user_marketing_opt_in_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deletion_requested_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="탈퇴 확정 시각"),
        ),
        migrations.AddField(
            model_name="user",
            name="deletion_scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="이 시각이 지나면 authentication.purge_deleted_accounts 가 하드 삭제한다",
                null=True,
                verbose_name="영구 삭제 예정 시각",
            ),
        ),
    ]
