# Generated by Django 5.0.1 on 2026-09-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_deletion_requested_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kakao_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="카카오 로그인 사용자의 앱별 회원번호(id). 이메일이 바뀌어도 불변.",
                max_length=32,
                null=True,
                unique=True,
                verbose_name="카카오 회원번호",
            ),
        ),
    ]
