# Generated by Django 5.0.1 on 2026-09-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_user_kakao_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="popup_state",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="팝업 키 → 노출/닫기 카운터. GET·PATCH /api/v1/auth/me/popup-state/",
                verbose_name="팝업 노출 상태",
            ),
        ),
    ]
