# Generated by Django 5.0.1 on 2026-09-12 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_user_popup_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramLoginState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("state", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "redirect_uri",
                    models.CharField(
                        help_text="authorize 에 쓴 값. 코드 교환 때 **글자 그대로** 다시 보내야 Meta 가 받아 준다 — 그래서 클라이언트가 다시 보내온 값을 믿지 않고 여기 저장한 값을 쓴다.",
                        max_length=500,
                        verbose_name="검증된 redirect_uri",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "consumed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="사용 시각"),
                ),
            ],
            options={
                "verbose_name": "Instagram 로그인 State",
                "verbose_name_plural": "Instagram 로그인 State 목록",
                "db_table": "ig_login_oauth_states",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="instagram_user_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Instagram Business Login 의 앱 스코프 사용자 ID. username 과 달리 불변.",
                max_length=32,
                null=True,
                unique=True,
                verbose_name="인스타그램 사용자 ID",
            ),
        ),
    ]
