# Generated by Django 5.0.1 on 2026-09-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_instagramloginstate_user_instagram_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="POST /api/v1/auth/me/email/ 로 신청한 주소. 인증되면 email 로 승격되고 비워진다.",
                max_length=254,
                verbose_name="인증 대기 중인 이메일",
            ),
        ),
    ]
