# Generated by Django 5.0.1 on 2026-10-08 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_user_pending_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="숫자만(01012345678). 본인확인을 마친 번호만 채워진다.",
                max_length=20,
                verbose_name="휴대폰 번호",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_reward_granted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="번호 등록 보상 지급 시각"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_source",
            field=models.CharField(
                blank=True,
                default="",
                help_text="sms = 우리 문자 인증 / kakao = 카카오 동의항목으로 받은 본인확인 번호",
                max_length=16,
                verbose_name="번호 출처",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="값이 있으면 본인확인 완료. phone 이 차 있는데 이게 비면 안 된다.",
                null=True,
                verbose_name="휴대폰 인증 시각",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sms_marketing_opt_in",
            field=models.BooleanField(default=False, verbose_name="광고성 문자·알림톡 수신 동의"),
        ),
        migrations.AddField(
            model_name="user",
            name="sms_marketing_opt_in_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="문자 수신 동의 시각"),
        ),
        migrations.CreateModel(
            name="PhoneVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "phone",
                    models.CharField(db_index=True, max_length=20, verbose_name="수신번호(숫자만)"),
                ),
                (
                    "code_hash",
                    models.CharField(
                        help_text="HMAC-SHA256(SECRET_KEY, '<phone>:<code>') — 평문은 어디에도 남지 않는다",
                        max_length=64,
                        verbose_name="인증번호 HMAC",
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(default=0, verbose_name="확인 시도 횟수"),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invalidated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="재발송 또는 시도 초과로 죽은 행. 만료와 달리 '다시 받아야 한다'는 뜻.",
                        null=True,
                        verbose_name="무효화 시각",
                    ),
                ),
                ("request_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "휴대폰 인증",
                "verbose_name_plural": "휴대폰 인증 목록",
                "db_table": "phone_verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "verified_at"], name="phone_verif_user_id_24d662_idx"
                    ),
                    models.Index(
                        fields=["phone", "created_at"], name="phone_verif_phone_deaeaf_idx"
                    ),
                ],
            },
        ),
    ]
