# Generated by Django 5.0.1 on 2026-05-14 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("integrations", "0013_alter_autodmcampaign_trigger_type"),
        ("workspace", "0002_workspace_plan_workspace_workspaces_plan_c35e25_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IGMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "external_media_id",
                    models.CharField(
                        db_index=True,
                        help_text="Meta Graph API 의 미디어 ID",
                        max_length=64,
                        verbose_name="Instagram Media ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "이미지"),
                            ("VIDEO", "동영상"),
                            ("CAROUSEL_ALBUM", "캐러셀"),
                        ],
                        default="IMAGE",
                        max_length=20,
                        verbose_name="미디어 타입",
                    ),
                ),
                (
                    "media_product_type",
                    models.CharField(
                        choices=[
                            ("FEED", "피드"),
                            ("REELS", "릴스"),
                            ("STORY", "스토리"),
                            ("AD", "광고"),
                        ],
                        default="FEED",
                        help_text="FEED / REELS / STORY / AD",
                        max_length=20,
                        verbose_name="미디어 제품 타입",
                    ),
                ),
                ("caption", models.TextField(blank=True, default="", verbose_name="캡션")),
                (
                    "permalink",
                    models.URLField(
                        blank=True, default="", max_length=512, verbose_name="원본 URL"
                    ),
                ),
                (
                    "media_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="IG 가 발급하는 일시 URL — 만료될 수 있음",
                        max_length=1024,
                        verbose_name="미디어 URL",
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True, default="", max_length=1024, verbose_name="썸네일 URL"
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="REELS / VIDEO 만 값 존재. 평균 시청 완료율 계산에 사용",
                        null=True,
                        verbose_name="영상 길이 (초)",
                    ),
                ),
                (
                    "children",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="캐러셀의 경우 자식 미디어 [{id, media_type, media_url}] 리스트. Meta API 한계로 자식별 좋아요/저장 분리는 불가능.",
                        verbose_name="캐러셀 자식 미디어",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True, help_text="IG 가 발급한 timestamp", verbose_name="게시 시각"
                    ),
                ),
                (
                    "metadata_last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="메타데이터 마지막 동기화 시각"
                    ),
                ),
                (
                    "insights_last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="인사이트 마지막 동기화 시각"
                    ),
                ),
                (
                    "insights_sync_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="403/100 등 에러 분류 — 권한 누락 안내용",
                        verbose_name="인사이트 동기화 마지막 에러",
                    ),
                ),
                (
                    "raw_metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="원본 메타데이터"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="integrations.igaccountconnection",
                        verbose_name="Instagram Account",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ig_media",
                        to="workspace.workspace",
                        verbose_name="Workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram Media",
                "verbose_name_plural": "Instagram Media",
                "db_table": "ig_media",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaSyncJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("metadata_only", "신규 미디어 메타데이터만"),
                            ("insights_recent", "최근 7일 인사이트"),
                            ("insights_all", "전체 인사이트"),
                        ],
                        default="insights_recent",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "대기"),
                            ("running", "실행 중"),
                            ("succeeded", "성공"),
                            ("failed", "실패"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("total", models.IntegerField(default=0, verbose_name="처리 대상 수")),
                ("processed", models.IntegerField(default=0, verbose_name="처리 완료 수")),
                ("error_count", models.IntegerField(default=0, verbose_name="에러 수")),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_jobs",
                        to="integrations.igaccountconnection",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ig_sync_jobs",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Sync Job",
                "verbose_name_plural": "Media Sync Jobs",
                "db_table": "ig_media_sync_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IGMediaInsight",
            fields=[
                (
                    "media",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="insight",
                        serialize=False,
                        to="insights.igmedia",
                        verbose_name="미디어",
                    ),
                ),
                ("reach", models.BigIntegerField(default=0, verbose_name="도달")),
                ("likes", models.BigIntegerField(default=0, verbose_name="좋아요")),
                ("comments", models.BigIntegerField(default=0, verbose_name="댓글")),
                ("shares", models.BigIntegerField(default=0, verbose_name="공유")),
                ("saved", models.BigIntegerField(default=0, verbose_name="저장")),
                (
                    "total_interactions",
                    models.BigIntegerField(
                        default=0,
                        help_text="likes+comments+shares+saved 합계 (Meta 제공)",
                        verbose_name="총 상호작용",
                    ),
                ),
                (
                    "views",
                    models.BigIntegerField(
                        blank=True,
                        help_text="REELS=재생 횟수, FEED 이미지=노출 수와 유사",
                        null=True,
                        verbose_name="조회수",
                    ),
                ),
                (
                    "impressions",
                    models.BigIntegerField(blank=True, null=True, verbose_name="노출 (FEED only)"),
                ),
                (
                    "follows",
                    models.BigIntegerField(blank=True, null=True, verbose_name="팔로우 전환"),
                ),
                (
                    "profile_visits",
                    models.BigIntegerField(blank=True, null=True, verbose_name="프로필 방문"),
                ),
                (
                    "profile_activity",
                    models.BigIntegerField(
                        blank=True,
                        help_text="프로필에서 발생한 클릭 등",
                        null=True,
                        verbose_name="프로필 액션",
                    ),
                ),
                (
                    "ig_reels_avg_watch_time_ms",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="릴스 평균 시청시간 (ms)"
                    ),
                ),
                (
                    "ig_reels_video_view_total_time_ms",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="릴스 누적 시청시간 (ms)"
                    ),
                ),
                (
                    "reels_skip_rate",
                    models.FloatField(
                        blank=True,
                        help_text="시청자가 첫 3초 이내 이탈한 비율 — '3초 훅' 진단 지표",
                        null=True,
                        verbose_name="릴스 스킵률 (%)",
                    ),
                ),
                (
                    "paid_reach",
                    models.BigIntegerField(blank=True, null=True, verbose_name="유료 도달"),
                ),
                (
                    "paid_impressions",
                    models.BigIntegerField(blank=True, null=True, verbose_name="유료 노출"),
                ),
                (
                    "paid_link_clicks",
                    models.BigIntegerField(blank=True, null=True, verbose_name="유료 링크 클릭"),
                ),
                (
                    "paid_website_visits",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="유료 웹사이트 방문"
                    ),
                ),
                (
                    "paid_spend",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="유료 지출 (원)",
                    ),
                ),
                (
                    "paid_currency",
                    models.CharField(blank=True, default="", max_length=8, verbose_name="통화"),
                ),
                (
                    "engagement_rate",
                    models.FloatField(
                        blank=True,
                        help_text="(likes+comments+saved+shares) / reach * 100",
                        null=True,
                        verbose_name="인게이지먼트율 (%)",
                    ),
                ),
                (
                    "viral_score",
                    models.FloatField(
                        blank=True,
                        help_text="(saved+shares) / reach * 100",
                        null=True,
                        verbose_name="저장/공유 비율 (%)",
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "fetched_at",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 fetch 시각"),
                ),
            ],
            options={
                "verbose_name": "Instagram Media Insight",
                "verbose_name_plural": "Instagram Media Insights",
                "db_table": "ig_media_insights",
                "indexes": [
                    models.Index(fields=["-fetched_at"], name="ig_media_in_fetched_17959a_idx"),
                    models.Index(
                        fields=["-engagement_rate"], name="ig_media_in_engagem_894477_idx"
                    ),
                    models.Index(fields=["-viral_score"], name="ig_media_in_viral_s_345006_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="igmedia",
            index=models.Index(
                fields=["workspace", "-published_at"], name="ig_media_workspa_e78587_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="igmedia",
            index=models.Index(
                fields=["account", "-published_at"], name="ig_media_account_fed0c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="igmedia",
            index=models.Index(
                fields=["workspace", "media_product_type", "-published_at"],
                name="ig_media_workspa_97ab37_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="igmedia",
            index=models.Index(fields=["external_media_id"], name="ig_media_externa_503175_idx"),
        ),
        migrations.AddConstraint(
            model_name="igmedia",
            constraint=models.UniqueConstraint(
                fields=("account", "external_media_id"), name="uniq_ig_media_per_account"
            ),
        ),
        migrations.AddIndex(
            model_name="mediasyncjob",
            index=models.Index(
                fields=["account", "-created_at"], name="ig_media_sy_account_9adf61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediasyncjob",
            index=models.Index(fields=["status"], name="ig_media_sy_status_47854f_idx"),
        ),
    ]
