# Generated by Django 5.0.1 on 2026-05-15 06:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0001_initial"),
        ("integrations", "0013_alter_autodmcampaign_trigger_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="IGAccountInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "period_days",
                    models.IntegerField(
                        default=30,
                        help_text="이 인사이트가 커버하는 일수 (기본 30일 — Meta 가 허용하는 최대 90일까지)",
                        verbose_name="기간 (일)",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="기간 시작")),
                ("period_end", models.DateField(verbose_name="기간 종료")),
                ("follower_reach", models.BigIntegerField(default=0, verbose_name="팔로워 도달")),
                (
                    "non_follower_reach",
                    models.BigIntegerField(default=0, verbose_name="비팔로워 도달"),
                ),
                ("unknown_reach", models.BigIntegerField(default=0, verbose_name="알 수 없음")),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audience_insights",
                        to="integrations.igaccountconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram Account Insight",
                "verbose_name_plural": "Instagram Account Insights",
                "db_table": "ig_account_insights",
                "indexes": [
                    models.Index(
                        fields=["account", "-fetched_at"], name="ig_account__account_6927a6_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="igaccountinsight",
            constraint=models.UniqueConstraint(
                fields=("account", "period_days"), name="uniq_ig_account_insight_period"
            ),
        ),
    ]
