# Generated by Django 5.0.1 on 2026-05-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0002_igaccountinsight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="igmedia",
            name="children",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="캐러셀의 경우 자식 미디어 [{id, media_type, media_url, thumbnail_url}] 리스트. Meta API 한계로 자식별 좋아요/저장 분리는 불가능. 자식 url 도 IG CDN 서명 쿼리스트링 포함이라 매우 길 수 있음 — JSON 이라 길이 제한 없음.",
                verbose_name="캐러셀 자식 미디어",
            ),
        ),
        migrations.AlterField(
            model_name="igmedia",
            name="media_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="IG CDN 의 서명된 일시 URL — 만료될 수 있음. 쿼리스트링 서명이 길어 VARCHAR 로는 부족 (1500~2000자), TextField 사용.",
                verbose_name="미디어 URL",
            ),
        ),
        migrations.AlterField(
            model_name="igmedia",
            name="thumbnail_url",
            field=models.TextField(blank=True, default="", verbose_name="썸네일 URL"),
        ),
    ]
