# Generated by Django 5.0.1 on 2026-05-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_rename_ses_to_provider"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emaillog",
            new_name="email_logs_templat_2ea189_idx",
            old_name="email_log_tmpl_status_idx",
        ),
        migrations.RenameIndex(
            model_name="emaillog",
            new_name="email_logs_to_emai_805955_idx",
            old_name="email_log_to_created_idx",
        ),
        migrations.RenameIndex(
            model_name="emailtoken",
            new_name="email_token_user_id_2c7b2a_idx",
            old_name="email_token_user_purpose_idx",
        ),
        migrations.RenameIndex(
            model_name="emailtoken",
            new_name="email_token_token_h_e36ef0_idx",
            old_name="email_token_hash_idx",
        ),
        migrations.RenameIndex(
            model_name="onboardingschedule",
            new_name="email_onboa_schedul_7dd0ad_idx",
            old_name="email_onboarding_sched_idx",
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="emailtoken",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="onboardingschedule",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
