# Generated by Django 5.0.1 on 2026-07-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0005_alter_emailtemplate_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="key",
            field=models.CharField(
                choices=[
                    ("email_verification", "email_verification"),
                    ("password_reset", "password_reset"),
                    ("welcome", "welcome"),
                    ("onboarding_day_3", "onboarding_day_3"),
                    ("onboarding_day_7", "onboarding_day_7"),
                    ("onboarding_day_14", "onboarding_day_14"),
                    ("payment_success", "payment_success"),
                    ("payment_failed", "payment_failed"),
                    ("pause_resume_reminder", "pause_resume_reminder"),
                    ("winback", "winback"),
                ],
                max_length=64,
                unique=True,
                verbose_name="Template Key",
            ),
        ),
    ]
