# Generated by Django 5.0.1 on 2026-08-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0008_alter_emailtemplate_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="key",
            field=models.CharField(
                choices=[
                    ("email_verification", "email_verification"),
                    ("password_reset", "password_reset"),
                    ("welcome", "welcome"),
                    ("onboarding_day_3", "onboarding_day_3"),
                    ("onboarding_day_7", "onboarding_day_7"),
                    ("onboarding_day_14", "onboarding_day_14"),
                    ("payment_success", "payment_success"),
                    ("payment_failed", "payment_failed"),
                    ("pause_resume_reminder", "pause_resume_reminder"),
                    ("winback", "winback"),
                    ("insta_report_ready", "insta_report_ready"),
                    ("conversion_consent", "conversion_consent"),
                    ("consent_missing_downgrade", "consent_missing_downgrade"),
                    ("admin_device_code", "admin_device_code"),
                ],
                max_length=64,
                unique=True,
                verbose_name="Template Key",
            ),
        ),
        migrations.AlterField(
            model_name="emailtoken",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("email_verify", "Email Verification"),
                    ("password_reset", "Password Reset"),
                    ("admin_device", "Admin Device Approval"),
                ],
                max_length=32,
            ),
        ),
    ]
